### ISSUE TITLE
SSL error in downloading translation models

### ISSUE THREAD

**Issue by 1nsunym** [googlesamples/mlkit#109]
Hello, I'm trying to test the `translate` app and I'm failing to fetch the any translation model either on the kotlin version or the java version.

Is there any extra measures I have to take before trying out the model?

I'm attaching failure log that show up on the android studio logcat.
It would be very helpful if someone knowledgeable could review it.

```
E/MLKitFbInstsRestClient: Connection error (or timeout) sending HTTPS POST request to <https://firebaseinstallations.googleapis.com/v1/projects/722550545529/installations>
    javax.net.ssl.SSLHandshakeException: Handshake failed
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:302)
        at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:188)
        at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:145)
        at okhttp3.internal.io.RealConnection.connect(RealConnection.java:108)
        at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:188)
        at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
        at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
        at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
        at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
        at okhttp3.RealCall.getResponse(RealCall.java:240)
        at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
        at okhttp3.RealCall.execute(RealCall.java:57)
        at com.google.android.gms.internal.mlkit_translate.zzhb.zza(com.google.mlkit:translate@@16.1.0:128)
        at com.google.android.gms.internal.mlkit_translate.zzhb.zzb(com.google.mlkit:translate@@16.1.0:24)
        at com.google.android.gms.internal.mlkit_translate.zzhb.zza(com.google.mlkit:translate@@16.1.0:160)
        at com.google.android.gms.internal.mlkit_translate.zzhe.zza(Unknown Source:6)
        at com.google.android.gms.internal.mlkit_translate.zzii.zza(com.google.mlkit:translate@@16.1.0:7)
        at com.google.android.gms.internal.mlkit_translate.zzhg.zza(com.google.mlkit:translate@@16.1.0:19)
        at com.google.android.gms.internal.mlkit_translate.zzhv.zza(com.google.mlkit:translate@@16.1.0:55)
        at com.google.android.gms.internal.mlkit_translate.zzhv.zza(com.google.mlkit:translate@@16.1.0:119)
        at com.google.android.gms.internal.mlkit_translate.zzhx.call(Unknown Source:8)
        at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
    	Suppressed: javax.net.ssl.SSLHandshakeException: Handshake failed
    		... 26 more
    	Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x7485e71808: Failure in SSL library, usually a protocol error
    error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (external/boringssl/src/ssl/tls_record.cc:251 0x7483bccecf:0x00000000)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:383)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:231)
        		... 25 more
     Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x7485e71808: Failure in SSL library, usually a protocol error
    error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (external/boringssl/src/ssl/tls_record.cc:251 0x7483bccecf:0x00000000)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:383)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:231)
        	... 25 more
```

**Comment by calren** [comment]
Hey @1nsunym , you shouldn't have to do anything extra to try out our sample apps.

Which app were you trying out? Was it the translate app or the translate-showcase app?

Might also be helpful for us to know if you saw this issue on an emulator or a specific device.

**Comment by 1nsunym** [comment]
Hi @calren, I feel so stupid.

It turned out to be a problem from some proxy configured on the wifi. It works fine with the LTE sim.

Regardless, thank you for trying to help.
