### ISSUE TITLE
LiveObjectDetection not working

### ISSUE THREAD

**Issue by yasiralijaved** [googlesamples/mlkit#112]
### Step 1: Describe your environment

  * Android device: Android Emulator
  * Android OS version: 10
  * Google Play Services version: 12451000
  
### Step 2: Describe the problem:

I get the following a lifecycle and observer related error in console/logcat while launching the LiveObjectDetection Activity. In result the Object detection is not working.

#### Steps to reproduce:

  1. Merge Barcode detection related code into LiveObjectDetection Activity
  2. Delete all un-used resources and classes
  3. run the app and launch the LiveObjectDetection Activity
  4. You will see the mentioned error in logcat and console of debug view
  
#### Observed Results:

* Logcat outout
Error preloading model resource
    com.google.mlkit.common.MlKitException: Internal error has occurred when executing ML Kit tasks
        at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@16.1.0:32)
        at com.google.mlkit.common.sdkinternal.zzl.run(Unknown Source:10)
        at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@16.1.0:3)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@16.1.0:24)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zza(com.google.mlkit:common@@16.1.0:30)
        at com.google.mlkit.common.sdkinternal.zzh.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalStateException: Method addObserver must be called on the main thread
        at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:172)
        at com.google.android.libraries.intelligence.acceleration.ProcessStateObserver.zza(com.google.mlkit:vision-internal-vkp@@17.0.0:10)
        at com.google.mlkit.vision.vkp.PipelineManager.start(com.google.mlkit:vision-internal-vkp@@17.0.0:128)
        at com.google.mlkit.vision.objects.defaults.internal.zzd.load(com.google.mlkit:object-detection@@16.2.0:74)
        at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@16.1.0:24)
        at com.google.mlkit.common.sdkinternal.zzl.run(Unknown Source:10) 
        at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@16.1.0:3) 
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@16.1.0:24) 
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zza(com.google.mlkit:common@@16.1.0:30) 
        at com.google.mlkit.common.sdkinternal.zzh.run(Unknown Source:2) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by SilverDestiny** [comment]
Hi Yasir,

The failure is caused by a recent change in androidx LifecycleRegistry: https://android-review.googlesource.com/c/platform/frameworks/support/+/1361476/1/lifecycle/lifecycle-runtime/src/main/java/androidx/lifecycle/LifecycleRegistry.java#172
They added `enforceMainThreadIfNeeded` recently to enforce main thread for addObserver

The fix will be in next release of ML Kit, which should be at the end of this month or early next month.
In the meantime, you can also change the app's build.gradle to depend on stable androidx lifecycle runtime version, e.g. androidx.lifecycle:lifecycle-runtime:2.2.0, which doesn't include this change above, to temporarily solve this issue.

**Comment by yasiralijaved** [comment]
Hi @SilverDestiny 
Thanks for pointing me to the right direction. Out of all the library imports, the given below library was the culprit that was forcefully using the latest lifecycle runtime.

> implementation "androidx.activity:activity-ktx:1.2.0-alpha07"

After removing this import, the code is working fine.
For anyone facing this issue in the future, Below is the list of all imports, with all of them the code is working fine.

>     implementation 'com.android.volley:volley:1.1.1'
>     implementation 'com.google.android.material:material:1.3.0-alpha02'
>     implementation "androidx.lifecycle:lifecycle-extensions:2.2.0"
>     implementation "androidx.annotation:annotation:1.1.0"
>     implementation "androidx.core:core-ktx:1.3.1"
>     implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0"
>     implementation 'androidx.preference:preference:1.1.1'
>     implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.72"
