### ISSUE TITLE
Crashes on Android app with target sdk 30 (Android 11)

### ISSUE THREAD

**Issue by baole** [googlesamples/mlkit#154]
I recently upgraded my app to Android 11 (compile sdk=30, target_sdk=30) and got this error while using Language identification

```
    java.lang.UnsatisfiedLinkError: No implementation found for long com.google.mlkit.nl.languageid.d.a.k(java.nio.MappedByteBuffer, long) (tried Java_com_google_mlkit_nl_languageid_d_a_k and Java_com_google_mlkit_nl_languageid_d_a_k__Ljava_nio_MappedByteBuffer_2J)
        at com.google.mlkit.nl.languageid.d.a.k(Native Method)
        at com.google.mlkit.nl.languageid.d.a.c(com.google.mlkit:language-id@@16.1.1:27)
        at com.google.mlkit.common.b.i.h(com.google.mlkit:common@@17.0.0:24)
        at com.google.mlkit.common.b.v.run(Unknown Source:10)
        at com.google.mlkit.common.b.z.run(com.google.mlkit:common@@17.0.0:3)
        at com.google.mlkit.common.b.h.f(com.google.mlkit:common@@17.0.0:24)
        at com.google.mlkit.common.b.h.c(com.google.mlkit:common@@17.0.0:30)
        at com.google.mlkit.common.b.r.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

SDK version: `implementation 'com.google.mlkit:language-id:16.1.1'`

Is that a known issue or I missed something?

**Comment by sheepmaster** [comment]
I just tried upgrading the quickstart app from compile_sdk and target_sdk 29 to 30 and didn't get this issue. From the stack trace, it looks like a native method is renamed, so the corresponding native symbol for the implementation isn't found. This shouldn't usually happen unless Proguard (or r8?) is misconfigured somehow. What is your Proguard configuration? Or are you doing anything else that could cause a method to be renamed?

**Comment by baole** [comment]
Thanks @sheepmaster. I'm not sure what was going wrong with my Proguard file, but after adding following lines, it works again.
```
-keep class com.google.mlkit.**  { *; }
-keep interface com.google.mlkit.**  { *; }

-keep class Java_com_google_mlkit**  { *; }
-keep interface Java_com_google_mlkit**  { *; }
```

**Comment by sheepmaster** [comment]
Glad to hear it! BTW, the second pair of lines is unnecessary: `Java_…` is the name of a native symbol, not the name of a class or interface.

**Comment by AlirezaHadjar** [comment]
Add this line to your app/build.gradle:
`implementation("com.squareup.okhttp3:okhttp:4.9.2")`
