### ISSUE TITLE
Barcode scanner firebase mlkit with dynamic feature module 

### ISSUE THREAD

**Issue by medha742** [googlesamples/mlkit#160]
Barcode scanning dependency  : 
implementation 'com.google.mlkit:barcode-scanning:16.0.3'

- I have duly followed the code for both mlkit barcode scanning module and on demand feature module google sample projects 
- The app works fine in debug mode , but in release apk I am getting this crash related to ComponentsService Registrar 
   Stack trace for crash : 

`2020-10-14 00:39:27.579 25263-25263/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.shiprocket.shiprocket, PID: 25263
    java.lang.RuntimeException: Unable to get provider com.google.mlkit.common.internal.MlKitInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.mlkit.common.internal.MlKitInitProvider" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.shiprocket.shiprocket-SgqJBOa02nUhwLHjT1PrIg==/base.apk", zip file "/data/app/com.shiprocket.shiprocket-SgqJBOa02nUhwLHjT1PrIg==/split_config.en.apk", zip file "/data/app/com.shiprocket.shiprocket-SgqJBOa02nUhwLHjT1PrIg==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.shiprocket.shiprocket-SgqJBOa02nUhwLHjT1PrIg==/lib/arm64, /system/lib64]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:6537)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6025)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5931)
        at android.app.ActivityThread.access$1200(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.mlkit.common.internal.MlKitInitProvider" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.shiprocket.shiprocket-SgqJBOa02nUhwLHjT1PrIg==/base.apk", zip file "/data/app/com.shiprocket.shiprocket-SgqJBOa02nUhwLHjT1PrIg==/split_config.en.apk", zip file "/data/app/com.shiprocket.shiprocket-SgqJBOa02nUhwLHjT1PrIg==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.shiprocket.shiprocket-SgqJBOa02nUhwLHjT1PrIg==/lib/arm64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:121)
        at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:1)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6521)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6025) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5931) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6810) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.shiprocket.shiprocket-SgqJBOa02nUhwLHjT1PrIg==/split_config.en.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:729)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:812)
        at android.app.LoadedApk.getResources(LoadedApk.java:1034)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2357)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5821)
2020-10-14 00:39:27.579 25263-25263/? E/AndroidRuntime: 		... 8 more
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.shiprocket.shiprocket-SgqJBOa02nUhwLHjT1PrIg==/split_config.xxhdpi.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:729)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:812)
        at android.app.LoadedApk.getResources(LoadedApk.java:1034)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2357)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5821)
        		... 8 more`

- These are the firebase dependencies I am using in app build.gradle module 

implementation 'com.google.firebase:firebase-crashlytics:17.2.2' 
implementation "com.google.firebase:firebase-messaging:20.3.0" 
implementation "com.google.firebase:firebase-config:19.2.0" 
implementation 'com.google.firebase:firebase-dynamic-links:19.1.1' 
implementation 'com.google.firebase:firebase-perf:19.0.9' 
implementation 'com.google.firebase:firebase-analytics:17.6.0' 
implementation 'com.google.firebase:firebase-appindexing:19.1.0'

The crash occurs on application launch even though the dynamic module has not been accessed yet .

**Comment by IlyaKubyskin** [comment]
Same issue. Any ideas how to fix this?

**Comment by happysingh23828** [comment]
I'm facing the same issue, any workaround or fix @IlyaKubyskin @medha742 ?

**Comment by McBodik** [comment]
Workaround for me was to place mlkit dependency to base module too.

**Comment by cs-googler** [comment]
Hi, I am not sure why this issue has never been answered by us. It is documented in the MLKit[ known issues](https://developers.google.com/ml-kit/known-issues) session.  We are looking at supporting this in future releases.

**Comment by jonneymendoza** [comment]
After moving this to the app module, i get this error:

```Installation did not succeed.
The application could not be installed: INSTALL_FAILED_INVALID_APK```

**Comment by rohitramkumar308** [comment]
We are not using dynamic modules but still getting this issue
Issue details:  https://github.com/googlesamples/mlkit/issues/277
