### ISSUE TITLE
ClassNotFoundException: Didn't find class "com.google.mlkit.vision.face.FaceDetectorOptions$Builder"

### ISSUE THREAD

**Issue by happysingh23828** [googlesamples/mlkit#188]
I have used mlkit in one of our SDK and it is getting crashes when I am using aar of the SDK. It is working in the SDK app, but when you generate aar out of it, it is not able to find mlkit dependencies.

Here is the log for it.

`2020-11-25 15:18:05.200 11768-11768/com.talview.candidate E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.talview.candidate, PID: 11768
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/mlkit/vision/face/FaceDetectorOptions$Builder;
        at com.talview.android.lib.media.camerax.facedetection.FaceContourDetectionProcessor.<init>(FaceContourDetectionProcessor.kt:18)
        at com.talview.android.lib.media.camerax.facedetection.CameraManager.selectAnalyzer(CameraManager.kt:68)
        at com.talview.android.lib.media.camerax.facedetection.CameraManager.access$selectAnalyzer(CameraManager.kt:16)
        at com.talview.android.lib.media.camerax.facedetection.CameraManager$startCamera$1.run(CameraManager.kt:54)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6702)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.mlkit.vision.face.FaceDetectorOptions$Builder" on path: DexPathList[[zip file "/data/app/com.talview.candidate-MXmRz1UcpTw-fJbE6xxC_Q==/base.apk"],nativeLibraryDirectories=`

**Dependecies**
    `const val mlKit = "com.google.android.gms:play-services-mlkit-face-detection:16.1.0"
`
**AndroidManifest**

`<meta-data
          android:name="com.google.mlkit.vision.DEPENDENCIES"
          android:value="face" />
      
      </application>`

**Comment by happysingh23828** [comment]
As aar doesn't contain any transitive dependencies, we need to provide either using fat-aar or need to add mlkit dependencies to project which is using aar.

I have fixed this by adding mlkit dependency in another project
