### ISSUE TITLE
MLKit Barcode recognize crash

### ISSUE THREAD

**Issue by ivan200** [googlesamples/mlkit#211]
Im trying to develop application with cameraX by [this](https://developers.google.com/ml-kit/vision/barcode-scanning/android) guide and internal crash happens

```
JNI DETECTED ERROR IN APPLICATION: field operation on NULL object: 0x0
    in call to GetLongField
    from com.google.android.libraries.barhopper.Barcode[] com.google.android.libraries.barhopper.BarhopperV2.recognizeBufferNative(long, int, int, java.nio.ByteBuffer, com.google.android.libraries.barhopper.RecognitionOptions)

at com.google.android.libraries.barhopper.BarhopperV2.recognizeBufferNative(Native method)
at com.google.android.libraries.barhopper.BarhopperV2.recognize(com.google.mlkit:barcode-scanning@@16.1.0:6)
at com.google.mlkit.vision.barcode.zza.zzc(com.google.mlkit:barcode-scanning@@16.1.0:24)
at com.google.mlkit.vision.barcode.internal.zzi.zzd(com.google.android.gms:play-services-mlkit-barcode-scanning@@16.1.3:12)
- locked <0x07f962c4> (a com.google.mlkit.vision.barcode.internal.zzi)
at com.google.mlkit.vision.barcode.internal.zzi.run(com.google.android.gms:play-services-mlkit-barcode-scanning@@16.1.3:-1)
at com.google.mlkit.vision.common.internal.MobileVisionBase.zza(com.google.mlkit:vision-common@@16.2.0:-1)
at com.google.mlkit.vision.common.internal.zzc.call(com.google.mlkit:vision-common@@16.2.0:-1)
at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@17.1.0:-1)
at com.google.mlkit.common.sdkinternal.zzn.run(com.google.mlkit:common@@17.1.0:-1)
at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@17.1.0:2)
at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@17.1.0:4)
at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@17.1.0:-1)
at com.google.mlkit.common.sdkinternal.zzj.run(com.google.mlkit:common@@17.1.0:-1)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@17.1.0:-1)
at com.google.mlkit.common.sdkinternal.zzk.run(com.google.mlkit:common@@17.1.0:-1)
at java.lang.Thread.run(Thread.java:919)
```

is this mlkit problem, or not?
(phone have no play services)
crash happens every time i launch my app
[full crashlog](https://github.com/googlesamples/mlkit/files/5742284/mlkit_crash.txt)

**Comment by ivan200** [comment]
After some debugging, I think I found the problem.
I probably closed imageProxy incorrectly

and in the 4th article of [this guide ](https://developers.google.com/ml-kit/vision/barcode-scanning/android#4.-process-the-image)
it seems that this piece of code is missing:
```
.addOnCompleteListener {
    imageProxy.close()
}
```

**Comment by steven-chengji-yan** [comment]
Hi John, glad you figured it out.

The guide you linked is a general guide, where the InputImage could be constructed in several different ways.
Only when you construct the InputImage from media.Image, you need to call the following:
.addOnCompleteListener {
    imageProxy.close()
}

And this is documented in the "Note" section right below the section your link points to.

Best,
Happy holidays!
