### ISSUE TITLE
Duplicate class issue

### ISSUE THREAD

**Issue by sripati** [googlesamples/mlkit#217]
I want use Android Barcode Scanning library **implementation 'com.google.mlkit:barcode-scanning:16.1.0'** getting compile time below error.

java.lang.RuntimeException: Duplicate class com.google.firebase.components.Component found in modules jetified-firebase-common-16.0.3-runtime.jar (com.google.firebase:firebase-common:16.0.3) and jetified-firebase-components-16.0.0-runtime.jar (com.google.firebase:firebase-components:16.0.0)
  Duplicate class com.google.firebase.components.Component$1 found in modules jetified-firebase-common-16.0.3-runtime.jar (com.google.firebase:firebase-common:16.0.3) and jetified-firebase-components-16.0.0-runtime.jar (com.google.firebase:firebase-components:16.0.0)
  Duplicate class com.google.firebase.components.Component$Builder found in modules jetified-firebase-common-16.0.3-runtime.jar (com.google.firebase:firebase-common:16.0.3) and jetified-firebase-components-16.0.0-runtime.jar (com.google.firebase:firebase-components:16.0.0)
  Duplicate class com.google.firebase.components.ComponentContainer found in modules jetified-firebase-common-16.0.3-runtime.jar (com.google.firebase:firebase-common:16.0.3) and jetified-firebase-components-16.0.0-runtime.jar (com.google.firebase:firebase-components:16.0.0)
  Duplicate class com.google.firebase.components.ComponentFactory found in modules jetified-firebase-common-16.0.3-runtime.jar (com.google.firebase:firebase-common:16.0.3) and jetified-firebase-components-16.0.0-runtime.jar (com.google.firebase:firebase-components:16.0.0)
  Duplicate class com.google.firebase.components.ComponentRegistrar found in modules jetified-firebase-common-16.0.3-runtime.jar (com.google.firebase:firebase-common:16.0.3) and jetified-firebase-components-16.0.0-runtime.jar (com.google.firebase:firebase-components:16.0.0)
  Duplicate class com.google.firebase.components.Dependency found in modules jetified-firebase-common-16.0.3-runtime.jar (com.google.firebase:firebase-common:16.0.3) and jetified-firebase-components-16.0.0-runtime.jar (com.google.firebase:firebase-components:16.0.0)
  Duplicate class com.google.firebase.components.DependencyCycleException found in modules jetified-firebase-common-16.0.3-runtime.jar (com.google.firebase:firebase-common:16.0.3) and jetified-firebase-components-16.0.0-runtime.jar (com.google.firebase:firebase-components:16.0.0)
  Duplicate class com.google.firebase.components.DependencyException found in modules jetified-firebase-common-16.0.3-runtime.jar (com.google.firebase:firebase-common:16.0.3) and jetified-firebase-components-16.0.0-runtime.jar (com.google.firebase:firebase-components:16.0.0)
  Duplicate class com.google.firebase.components.MissingDependencyException found in modules jetified-firebase-common-16.0.3-runtime.jar (com.google.firebase:firebase-common:16.0.3) and jetified-firebase-components-16.0.0-runtime.jar (com.google.firebase:firebase-components:16.0.0)
  Duplicate class com.google.firebase.events.Event found in modules jetified-firebase-common-16.0.3-runtime.jar (com.google.firebase:firebase-common:16.0.3) and jetified-firebase-components-16.0.0-runtime.jar (com.google.firebase:firebase-components:16.0.0)
  Duplicate class com.google.firebase.events.EventHandler found in modules jetified-firebase-common-16.0.3-runtime.jar (com.google.firebase:firebase-common:16.0.3) and jetified-firebase-components-16.0.0-runtime.jar (com.google.firebase:firebase-components:16.0.0)
  Duplicate class com.google.firebase.events.Publisher found in modules jetified-firebase-common-16.0.3-runtime.jar (com.google.firebase:firebase-common:16.0.3) and jetified-firebase-components-16.0.0-runtime.jar (com.google.firebase:firebase-components:16.0.0)
  Duplicate class com.google.firebase.events.Subscriber found in modules jetified-firebase-common-16.0.3-runtime.jar (com.google.firebase:firebase-common:16.0.3) and jetified-firebase-components-16.0.0-runtime.jar (com.google.firebase:firebase-components:16.0.0)
  Duplicate class com.google.firebase.inject.Provider found in modules jetified-firebase-common-16.0.3-runtime.jar (com.google.firebase:firebase-common:16.0.3) and jetified-firebase-components-16.0.0-runtime.jar (com.google.firebase:firebase-components:16.0.0)
  
When I am trying to exclude **com.google.firebase:firebase-components** getting runtime below error

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/components/ComponentDiscovery;
        at com.google.mlkit.common.sdkinternal.MlKitContext.zza(com.google.mlkit:common@@17.1.0:2)
        at com.google.mlkit.common.internal.MlKitInitProvider.onCreate(com.google.mlkit:common@@17.1.0:3)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2154)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2128)
        at com.google.mlkit.common.internal.MlKitInitProvider.attachInfo(com.google.mlkit:common@@17.1.0:3)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7279)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6764)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6614)
        at android.app.ActivityThread.access$1600(ActivityThread.java:231)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1952)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.components.ComponentDiscovery" on path: DexPathList[[zip file "/data/app/com.nuvizz.di.android-rFcw3oqis_XdJOMi8xdZ9g==/base.apk"],nativeLibraryDirectories=[/data/app/com.nuvizz.di.android-rFcw3oqis_XdJOMi8xdZ9g==/lib/arm64, /data/app/com.xyz-rFcw3oqis_XdJOMi8xdZ9g==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.mlkit.common.sdkinternal.MlKitContext.zza(com.google.mlkit:common@@17.1.0:2) 
        at com.google.mlkit.common.internal.MlKitInitProvider.onCreate(com.google.mlkit:common@@17.1.0:3) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2154) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2128) 
        at com.google.mlkit.common.internal.MlKitInitProvider.attachInfo(com.google.mlkit:common@@17.1.0:3) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:7279) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6764) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6614) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:231) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1952) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7682) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 

Please help me on this how to proceed further and let me know if any other information required. **Note : minifyEnabled true**

**Comment by swiyu** [comment]
Could you share your all dependencies? looks like you have mixed version dependencies, which depends on both firebase-components-16.0.0 and firebase-components-16.0.3.

**Comment by swiyu** [comment]
You may depend on some very old Firebase SDK, which could cause conflict with ML Kit. If possible, could you upgrade your other Firebase dependencies, so that the issue could go away.

**Comment by sripati** [comment]
Thanks for the support. Yes, I have upgraded to my firebase-messaging to latest version, it works fins.
