### ISSUE TITLE
Crash issue with MLKit Pose Detection

### ISSUE THREAD

**Issue by duckyngo** [googlesamples/mlkit#228]
I run MLKit pose detection on the Samsung S7 Phone and it has a crash issue sometimes.
Some Information:
- Device: Samsung Galaxy S7
- Pose detection dependency: com.google.mlkit:pose-detection:17.0.1-beta1

`2021-01-20 16:36:50.449 6372-6372/io.aithe.aithe_9pose E/PoseDetectorProcessor: Pose detection failed!
    com.google.mlkit.common.MlKitException: Couldn't send input frame. Possible reason: load() hasn't been called yet.
        at com.google.mlkit.vision.mediapipe.MediaPipeGraphRunner.run(com.google.mlkit:mediapipe-internal@@16.0.1-beta1:5)
        at com.google.mlkit.vision.pose.internal.zzd.run(Unknown Source:96)
        at com.google.mlkit.vision.common.internal.MobileVisionBase.zza(Unknown Source:2)
        at com.google.mlkit.vision.common.internal.zzc.call(Unknown Source:4)
        at com.google.mlkit.common.sdkinternal.ModelResource.zza(Unknown Source:37)
        at com.google.mlkit.common.sdkinternal.zzn.run(Unknown Source:10)
        at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@17.1.0:2)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@17.1.0:4)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(Unknown Source:8)
        at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(Unknown Source:10)
        at com.google.mlkit.common.sdkinternal.zzk.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:764)
`

I think it's because of JNI loading issuse:
`2021-01-20 16:36:49.557 6372-7662/io.aithe.aithe_9pose E/System: Unable to open zip file: /data/app/io.aithe.aithe_9pose-7HZVmWYauSSFKUBX3ALJXw==/base.apk
2021-01-20 16:36:49.561 6372-7662/io.aithe.aithe_9pose E/System: java.io.FileNotFoundException: File doesn't exist: /data/app/io.aithe.aithe_9pose-7HZVmWYauSSFKUBX3ALJXw==/base.apk
        at java.util.zip.ZipFile.<init>(ZipFile.java:212)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.jar.JarFile.<init>(JarFile.java:160)
        at java.util.jar.JarFile.<init>(JarFile.java:97)
        at libcore.io.ClassPathURLStreamHandler.<init>(ClassPathURLStreamHandler.java:47)
        at dalvik.system.DexPathList$NativeLibraryElement.maybeInit(DexPathList.java:761)
        at dalvik.system.DexPathList$NativeLibraryElement.findNativeLibrary(DexPathList.java:782)
        at dalvik.system.DexPathList.findLibrary(DexPathList.java:528)
        at dalvik.system.BaseDexClassLoader.findLibrary(BaseDexClassLoader.java:122)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1005)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.google.mlkit.vision.mediapipe.zze.<clinit>(com.google.mlkit:mediapipe-internal@@16.0.1-beta1:3)
        at com.google.mlkit.vision.mediapipe.MediaPipeGraphRunner.load(com.google.mlkit:mediapipe-internal@@16.0.1-beta1:3)
        at com.google.mlkit.vision.pose.internal.zzd.load(com.google.mlkit:pose-detection-common@@17.0.1-beta1:9)
        at com.google.mlkit.common.sdkinternal.ModelResource.zza(Unknown Source:18)
        at com.google.mlkit.common.sdkinternal.zzn.run(Unknown Source:10)
        at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@17.1.0:2)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@17.1.0:4)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(Unknown Source:8)
        at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(Unknown Source:10)
        at com.google.mlkit.common.sdkinternal.zzk.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:764)
2021-01-20 16:36:49.563 6372-7662/io.aithe.aithe_9pose E/zze: Failed to load JNI: 
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/io.aithe.aithe_9pose-7HZVmWYauSSFKUBX3ALJXw==/base.apk"],nativeLibraryDirectories=[/data/app/io.aithe.aithe_9pose-7HZVmWYauSSFKUBX3ALJXw==/lib/arm64, /data/app/io.aithe.aithe_9pose-7HZVmWYauSSFKUBX3ALJXw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libxeno_native.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.google.mlkit.vision.mediapipe.zze.<clinit>(com.google.mlkit:mediapipe-internal@@16.0.1-beta1:3)
        at com.google.mlkit.vision.mediapipe.MediaPipeGraphRunner.load(com.google.mlkit:mediapipe-internal@@16.0.1-beta1:3)
        at com.google.mlkit.vision.pose.internal.zzd.load(com.google.mlkit:pose-detection-common@@17.0.1-beta1:9)
        at com.google.mlkit.common.sdkinternal.ModelResource.zza(Unknown Source:18)
        at com.google.mlkit.common.sdkinternal.zzn.run(Unknown Source:10)
        at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@17.1.0:2)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@17.1.0:4)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(Unknown Source:8)
        at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(Unknown Source:10)
        at com.google.mlkit.common.sdkinternal.zzk.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:764)
2021-01-20 16:36:49.563 6372-7662/io.aithe.aithe_9pose E/zygote64: No implementation found for boolean com.google.android.gms.internal.mlkit_vision_mediapipe.zzdu.zzb(android.content.Context, java.lang.String) (tried Java_com_google_android_gms_internal_mlkit_1vision_1mediapipe_zzdu_zzb and Java_com_google_android_gms_internal_mlkit_1vision_1mediapipe_zzdu_zzb__Landroid_content_Context_2Ljava_lang_String_2)
2021-01-20 16:36:49.565 6372-7662/io.aithe.aithe_9pose E/AndroidRuntime: FATAL EXCEPTION: pool-12-thread-1
    Process: io.aithe.aithe_9pose, PID: 6372
    java.lang.UnsatisfiedLinkError: No implementation found for boolean com.google.android.gms.internal.mlkit_vision_mediapipe.zzdu.zzb(android.content.Context, java.lang.String) (tried Java_com_google_android_gms_internal_mlkit_1vision_1mediapipe_zzdu_zzb and Java_com_google_android_gms_internal_mlkit_1vision_1mediapipe_zzdu_zzb__Landroid_content_Context_2Ljava_lang_String_2)
        at com.google.android.gms.internal.mlkit_vision_mediapipe.zzdu.zzb(Native Method)
        at com.google.android.gms.internal.mlkit_vision_mediapipe.zzdu.zza(com.google.mlkit:mediapipe-internal@@16.0.1-beta1:2)
        at com.google.mlkit.vision.mediapipe.zze.zza(com.google.mlkit:mediapipe-internal@@16.0.1-beta1:1)
        at com.google.mlkit.vision.mediapipe.MediaPipeGraphRunner.load(com.google.mlkit:mediapipe-internal@@16.0.1-beta1:4)
        at com.google.mlkit.vision.pose.internal.zzd.load(com.google.mlkit:pose-detection-common@@17.0.1-beta1:9)
        at com.google.mlkit.common.sdkinternal.ModelResource.zza(Unknown Source:18)
        at com.google.mlkit.common.sdkinternal.zzn.run(Unknown Source:10)
        at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@17.1.0:2)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@17.1.0:4)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(Unknown Source:8)
        at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(Unknown Source:10)
        at com.google.mlkit.common.sdkinternal.zzk.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:764)`

**Comment by swiyu** [comment]
Are you using App bundle or dynamic feature for your app?

**Comment by duckyngo** [comment]
No, I didn't use App bundle or any dynamic feature. Also, I see that the issue appear just when the battery is low (<20%)

**Comment by steven-chengji-yan** [comment]
Hi duckyngo,

When the batter is <20%, is it 100% reproducible?
Also, is it only an issue on that device or also happen on other devices?

**Comment by duckyngo** [comment]
I am sorry, I notice that this issue appears when I using Glide to show a GIF as an activity's background. It's not 100% reproducible just around 50%. After I remove the Glide code, the issue is no longer appear.

**Comment by steven-chengji-yan** [comment]
Interesting.. but glad you found the cause.

**Comment by duckyngo** [comment]
Yeah, Because It doesn’t happen before so I can find the cause. We tested on 3 devices ( Samsung S10Plus, LG Q8, and Samsung S7). The issue only occurs on Samsung S7.
