### ISSUE TITLE
TextRecognizerCreator: Not allowed since feature flag for ML Kit is not enabled

### ISSUE THREAD

**Issue by rsteimen** [googlesamples/mlkit#236]
Text recognition "com.google.android.gms:play-services-mlkit-text-recognition:16.1.3" is not working at all on the device "Sony G8441 Android 9, API 28". Older version "com.google.firebase:firebase-ml-vision:24.0.3" works fine. We could not find any resource documenting how to "enable feature flag for ML Kit".

**Reproduce**
1. Clone https://github.com/googlesamples/mlkit
2. Run vision-quickstart

The error occurs with LivePreviewActivity, StillImageActicity and CameraXLivePreviewActivity within the demo app.

**Console output**
```
2021-02-05 10:23:55.329 11428-11491/? E/TextRecognizerCreator: Not allowed since feature flag for ML Kit is not enabled.
2021-02-05 10:23:55.573 11428-11428/? E/MobileVisionBase: Error preloading model resource
    c.a.d.a.a: Failed to init thin text recognizer.
        at com.google.mlkit.vision.text.internal.b.zza(Unknown Source:47)
        at com.google.mlkit.vision.text.internal.n.b(Unknown Source:3)
        at c.a.d.a.c.k.f(Unknown Source:18)
        at c.a.d.a.c.b0.run(Unknown Source:10)
        at c.a.d.a.c.d0.run(Unknown Source:10)
        at c.a.d.a.c.j.e(Unknown Source:13)
        at c.a.d.a.c.j.c(Unknown Source:8)
        at c.a.d.a.c.x.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at c.a.d.a.c.j.d(Unknown Source:10)
        at c.a.d.a.c.y.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.os.RemoteException: Not allowed since feature flag for ML Kit is not enabled.
        at ik.a(:com.google.android.gms.optional_vision_ocr@204714065@20.47.14 (100400-0):0)
        at com.google.android.gms.vision.text.mlkit.TextRecognizerCreator.newTextRecognizer(:com.google.android.gms.optional_vision_ocr@204714065@20.47.14 (100400-0):11)
        at com.google.android.gms.vision.text.mlkit.TextRecognizerCreator.newTextRecognizer(:com.google.android.gms.optional_vision_ocr@204714065@20.47.14 (100400-0):0)
        at mv.u(:com.google.android.gms.optional_vision_ocr@204714065@20.47.14 (100400-0):4)
        at ak.onTransact(:com.google.android.gms.optional_vision_ocr@204714065@20.47.14 (100400-0):4)
        at android.os.Binder.transact(Binder.java:667)
        at c.a.a.b.f.p.a.Q(Unknown Source:7)
        at c.a.a.b.f.p.qa.f(Unknown Source:8)
        at com.google.mlkit.vision.text.internal.b.zza(Unknown Source:30)
        at com.google.mlkit.vision.text.internal.n.b(Unknown Source:3) 
        at c.a.d.a.c.k.f(Unknown Source:18) 
        at c.a.d.a.c.b0.run(Unknown Source:10) 
        at c.a.d.a.c.d0.run(Unknown Source:10) 
        at c.a.d.a.c.j.e(Unknown Source:13) 
        at c.a.d.a.c.j.c(Unknown Source:8) 
        at c.a.d.a.c.x.run(Unknown Source:2) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at c.a.d.a.c.j.d(Unknown Source:10) 
        at c.a.d.a.c.y.run(Unknown Source:2) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by swiyu** [comment]
The feature flag should already be enabled everywhere, it may due to your play services have not received the update. Could you try to reboot your device or update your Google Play Service in that device.

**Comment by rsteimen** [comment]
Thanks swiyu for your quick response. A device reboot resolved the issue completely. It works now as expected.
Before device reboot, Google Maps didn't find my GPS position. After a reboot that also worked without problems. It's unclear if these issues are related.

**Comment by deputat007** [comment]
After upgrading the Text Recognition dependency from 16.1.1 to 16.1.3:


    com.google.android.gms:play-services-mlkit-text-recognition:16.1.3

   
on Realme 3 Pro Android 10, the app starts crashing when calling 
    `TextRecognition.getClient().process(InputImage.fromFilePath(context, data)).await()`

here is the stack trace from firebase:

    Non-fatal Exception: f.b.e.a.a: Failed to init thin text recognizer.
       at com.google.mlkit.vision.text.internal.zzb.zza(zzb.java:47)
       at com.google.mlkit.vision.text.internal.zzn.load(zzn.java:3)
       at com.google.mlkit.common.sdkinternal.ModelResource.zza(ModelResource.java:18)
       at com.google.mlkit.common.sdkinternal.zzn.run(zzn.java:10)
       at com.google.mlkit.common.sdkinternal.zzp.run(zzp.java:10)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(MlKitThreadPool.java:13)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(MlKitThreadPool.java:8)
       at com.google.mlkit.common.sdkinternal.zzj.run(zzj.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(MlKitThreadPool.java:10)
       at com.google.mlkit.common.sdkinternal.zzk.run(zzk.java:2)
       at java.lang.Thread.run(Thread.java:919)

 
    Caused by android.os.RemoteException: Not allowed since feature flag for ML Kit is not enabled.
       at ii.a(ii.java)
       at com.google.android.gms.vision.text.mlkit.TextRecognizerCreator.newTextRecognizer(TextRecognizerCreator.java:11)
       at com.google.android.gms.vision.text.mlkit.TextRecognizerCreator.newTextRecognizer(TextRecognizerCreator.java)
       at mu.u(mu.java:4)
       at al.onTransact(al.java:4)
       at android.os.Binder.transact(Binder.java:914)
       at com.google.android.gms.internal.mlkit_vision_text.zza.zzb(zza.java:7)
       at com.google.android.gms.internal.mlkit_vision_text.zzlh.zzd(zzlh.java:8)
       at com.google.mlkit.vision.text.internal.zzb.zza(zzb.java:30)
       at com.google.mlkit.vision.text.internal.zzn.load(zzn.java:3)
       at com.google.mlkit.common.sdkinternal.ModelResource.zza(ModelResource.java:18)
       at com.google.mlkit.common.sdkinternal.zzn.run(zzn.java:10)
       at com.google.mlkit.common.sdkinternal.zzp.run(zzp.java:10)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(MlKitThreadPool.java:13)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(MlKitThreadPool.java:8)
       at com.google.mlkit.common.sdkinternal.zzj.run(zzj.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(MlKitThreadPool.java:10)
       at com.google.mlkit.common.sdkinternal.zzk.run(zzk.java:2)
       at java.lang.Thread.run(Thread.java:919)

Google Play services are already updated and rebooting doesn't help

**Comment by zhouyiself** [comment]
> After upgrading the Text Recognition dependency from 16.1.1 to 16.1.3:
> 
> ```
> com.google.android.gms:play-services-mlkit-text-recognition:16.1.3
> ```
> 
> on Realme 3 Pro Android 10, the app starts crashing when calling
> `TextRecognition.getClient().process(InputImage.fromFilePath(context, data)).await()`
> 
> here is the stack trace from firebase:
> 
> ```
> Non-fatal Exception: f.b.e.a.a: Failed to init thin text recognizer.
>    at com.google.mlkit.vision.text.internal.zzb.zza(zzb.java:47)
>    at com.google.mlkit.vision.text.internal.zzn.load(zzn.java:3)
>    at com.google.mlkit.common.sdkinternal.ModelResource.zza(ModelResource.java:18)
>    at com.google.mlkit.common.sdkinternal.zzn.run(zzn.java:10)
>    at com.google.mlkit.common.sdkinternal.zzp.run(zzp.java:10)
>    at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(MlKitThreadPool.java:13)
>    at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(MlKitThreadPool.java:8)
>    at com.google.mlkit.common.sdkinternal.zzj.run(zzj.java:2)
>    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>    at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(MlKitThreadPool.java:10)
>    at com.google.mlkit.common.sdkinternal.zzk.run(zzk.java:2)
>    at java.lang.Thread.run(Thread.java:919)
> 
> 
> Caused by android.os.RemoteException: Not allowed since feature flag for ML Kit is not enabled.
>    at ii.a(ii.java)
>    at com.google.android.gms.vision.text.mlkit.TextRecognizerCreator.newTextRecognizer(TextRecognizerCreator.java:11)
>    at com.google.android.gms.vision.text.mlkit.TextRecognizerCreator.newTextRecognizer(TextRecognizerCreator.java)
>    at mu.u(mu.java:4)
>    at al.onTransact(al.java:4)
>    at android.os.Binder.transact(Binder.java:914)
>    at com.google.android.gms.internal.mlkit_vision_text.zza.zzb(zza.java:7)
>    at com.google.android.gms.internal.mlkit_vision_text.zzlh.zzd(zzlh.java:8)
>    at com.google.mlkit.vision.text.internal.zzb.zza(zzb.java:30)
>    at com.google.mlkit.vision.text.internal.zzn.load(zzn.java:3)
>    at com.google.mlkit.common.sdkinternal.ModelResource.zza(ModelResource.java:18)
>    at com.google.mlkit.common.sdkinternal.zzn.run(zzn.java:10)
>    at com.google.mlkit.common.sdkinternal.zzp.run(zzp.java:10)
>    at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(MlKitThreadPool.java:13)
>    at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(MlKitThreadPool.java:8)
>    at com.google.mlkit.common.sdkinternal.zzj.run(zzj.java:2)
>    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>    at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(MlKitThreadPool.java:10)
>    at com.google.mlkit.common.sdkinternal.zzk.run(zzk.java:2)
>    at java.lang.Thread.run(Thread.java:919)
> ```
> 
> Google Play services are already updated and rebooting doesn't help

Can you try to clean up Google Play Store app data and see if it works (Settings -> Apps & notification -> Google Play services -> Storage & cache -> Clear storage )

**Comment by deputat007** [comment]
> > After upgrading the Text Recognition dependency from 16.1.1 to 16.1.3:
> > ```
> > com.google.android.gms:play-services-mlkit-text-recognition:16.1.3
> > ```
> > 
> > 
> > on Realme 3 Pro Android 10, the app starts crashing when calling
> > `TextRecognition.getClient().process(InputImage.fromFilePath(context, data)).await()`
> > here is the stack trace from firebase:
> > ```
> > Non-fatal Exception: f.b.e.a.a: Failed to init thin text recognizer.
> >    at com.google.mlkit.vision.text.internal.zzb.zza(zzb.java:47)
> >    at com.google.mlkit.vision.text.internal.zzn.load(zzn.java:3)
> >    at com.google.mlkit.common.sdkinternal.ModelResource.zza(ModelResource.java:18)
> >    at com.google.mlkit.common.sdkinternal.zzn.run(zzn.java:10)
> >    at com.google.mlkit.common.sdkinternal.zzp.run(zzp.java:10)
> >    at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(MlKitThreadPool.java:13)
> >    at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(MlKitThreadPool.java:8)
> >    at com.google.mlkit.common.sdkinternal.zzj.run(zzj.java:2)
> >    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> >    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> >    at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(MlKitThreadPool.java:10)
> >    at com.google.mlkit.common.sdkinternal.zzk.run(zzk.java:2)
> >    at java.lang.Thread.run(Thread.java:919)
> > 
> > 
> > Caused by android.os.RemoteException: Not allowed since feature flag for ML Kit is not enabled.
> >    at ii.a(ii.java)
> >    at com.google.android.gms.vision.text.mlkit.TextRecognizerCreator.newTextRecognizer(TextRecognizerCreator.java:11)
> >    at com.google.android.gms.vision.text.mlkit.TextRecognizerCreator.newTextRecognizer(TextRecognizerCreator.java)
> >    at mu.u(mu.java:4)
> >    at al.onTransact(al.java:4)
> >    at android.os.Binder.transact(Binder.java:914)
> >    at com.google.android.gms.internal.mlkit_vision_text.zza.zzb(zza.java:7)
> >    at com.google.android.gms.internal.mlkit_vision_text.zzlh.zzd(zzlh.java:8)
> >    at com.google.mlkit.vision.text.internal.zzb.zza(zzb.java:30)
> >    at com.google.mlkit.vision.text.internal.zzn.load(zzn.java:3)
> >    at com.google.mlkit.common.sdkinternal.ModelResource.zza(ModelResource.java:18)
> >    at com.google.mlkit.common.sdkinternal.zzn.run(zzn.java:10)
> >    at com.google.mlkit.common.sdkinternal.zzp.run(zzp.java:10)
> >    at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(MlKitThreadPool.java:13)
> >    at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(MlKitThreadPool.java:8)
> >    at com.google.mlkit.common.sdkinternal.zzj.run(zzj.java:2)
> >    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> >    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> >    at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(MlKitThreadPool.java:10)
> >    at com.google.mlkit.common.sdkinternal.zzk.run(zzk.java:2)
> >    at java.lang.Thread.run(Thread.java:919)
> > ```
> > 
> > 
> > Google Play services are already updated and rebooting doesn't help
> 
> Can you try to clean up Google Play Store app data and see if it works (Settings -> Apps & notification -> Google Play services -> Storage & cache -> Clear storage )

still the same

**Comment by zhouyiself** [comment]
What's the version of your Google Play services app?

**Comment by deputat007** [comment]
> What's the version of your Google Play services app?

4.3.5

**Comment by zhouyiself** [comment]
Hmm, this doesn't seem to be a version of Google Play services app, latest one is 21.10.12.

**Comment by deputat007** [comment]
> Hmm, this doesn't seem to be a version of Google Play services app, latest one is 21.10.12.

I don't have an explicit dependency of Google Play Services only Firebase Android BoM 26.6.0 and Google Play services plugin 4.3.5

**Comment by zhouyiself** [comment]
Text Recognizer depends on Google Play Services internally to download the pipeline, and the feature flag issue might due to your Google Play Services app has some issues on syncing the correct flag value. This is why I suggested to update your Google Play Services and clean up its data.

**Comment by deputat007** [comment]
> Text Recognizer depends on Google Play Services internally to download the pipeline, and the feature flag issue might due to your Google Play Services app has some issues on syncing the correct flag value. This is why I suggested to update your Google Play Services and clean up its data.

sorry I thought you meant the dependency not the app.
version of Google Play services app is 21.06.13(the latest for this device)

**Comment by deputat007** [comment]
> This is why I suggested to update your Google Play Services and clean up its data.

I already did it, but it still doesn't work
