### ISSUE TITLE
`java.lang.IllegalStateException: This job has not completed yet` exception?

### ISSUE THREAD

**Issue by yektasarioglu** [googlesamples/mlkit#240]
Hi, I'm trying to write an instrumentation test for `translate(...)`. And  I got an error that throws `java.lang.IllegalStateException: This job has not completed yet`. Any ideas about how to solve this issue? 

``` kotlin
suspend fun translate(value: String = TEST_EXAMPLE) = suspendCoroutine<String> { continuation ->
        downloadModels(onSuccess = {
            translator.translate(value)
                .addOnSuccessListener {
                    Timber.d("Translated result is $it")
                    continuation.resume(it)
                }
                .addOnFailureListener {
                    Timber.e("Exception is $it")
                    continuation.resume(it.message ?: "Wow, something is wrong!")
                }
        })
    }
```

```
java.lang.IllegalStateException: This job has not completed yet
	at kotlinx.coroutines.JobSupport.getCompletionExceptionOrNull(JobSupport.kt:1187)
	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest(TestBuilders.kt:53)
	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest(TestBuilders.kt:80)
```

**Comment by yektasarioglu** [comment]
The exception was thrown at the invoking line of the test. Using `runBlocking` instead of `coroutinesTestRule.testDispatcher.runBlockingTest` solved the problem somehow 😕.  Anyone who could reveal some useful insight is more than welcome to reopen the issue and share their solutions.
