### ISSUE TITLE
Ml Translate Exception (Model name expected to be matching)

### ISSUE THREAD

**Issue by tmxdyf** [googlesamples/mlkit#256]
Hello, when I use machine translation kit to perform a large number of translations, this exception occasionally causes the program to crash. I hope I can get your help. Thank you.
```
04-01 15:01:35.934 11691 11691 E AndroidRuntime: com.google.android.gms.tasks.RuntimeExecutionException: java.lang.IllegalArgumentException: Model name expected to be matching [a-z]{2,3}_[a-z]{2,3}
04-01 15:01:35.934 11691 11691 E AndroidRuntime: 	at com.google.android.gms.tasks.zzu.getResult(com.google.android.gms:play-services-tasks@@17.1.0:15)
04-01 15:01:35.934 11691 11691 E AndroidRuntime: 	at com.google.mlkit.nl.translate.internal.zzv.zza(com.google.mlkit:translate@@16.1.1:41)
04-01 15:01:35.934 11691 11691 E AndroidRuntime: 	at com.google.mlkit.nl.translate.internal.zzac.onComplete(Unknown Source:2)
04-01 15:01:35.934 11691 11691 E AndroidRuntime: 	at com.google.android.gms.tasks.zzj.run(com.google.android.gms:play-services-tasks@@17.1.0:4)
04-01 15:01:35.934 11691 11691 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
04-01 15:01:35.934 11691 11691 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-01 15:01:35.934 11691 11691 E AndroidRuntime: 	at com.google.android.gms.internal.tasks.zzb.dispatchMessage(com.google.android.gms:play-services-tasks@@17.1.0:6)
04-01 15:01:35.934 11691 11691 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:201)
04-01 15:01:35.934 11691 11691 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6815)
04-01 15:01:35.934 11691 11691 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-01 15:01:35.934 11691 11691 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
04-01 15:01:35.934 11691 11691 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
04-01 15:01:35.934 11691 11691 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Model name expected to be matching [a-z]{2,3}_[a-z]{2,3}
04-01 15:01:35.934 11691 11691 E AndroidRuntime: 	at com.google.mlkit.nl.translate.internal.zzu.zzc(com.google.mlkit:translate@@16.1.1:35)
04-01 15:01:35.934 11691 11691 E AndroidRuntime: 	at com.google.mlkit.nl.translate.internal.zzu.zzb(com.google.mlkit:translate@@16.1.1:22)
04-01 15:01:35.934 11691 11691 E AndroidRuntime: 	at com.google.mlkit.nl.translate.internal.zzc.zza(com.google.mlkit:translate@@16.1.1:124)
04-01 15:01:35.934 11691 11691 E AndroidRuntime: 	at com.google.mlkit.nl.translate.internal.zzo.zza(com.google.mlkit:translate@@16.1.1:32)
04-01 15:01:35.934 11691 11691 E AndroidRuntime: 	at com.google.mlkit.nl.translate.internal.zzv.zza(com.google.mlkit:translate@@16.1.1:51)
04-01 15:01:35.934 11691 11691 E AndroidRuntime: 	at com.google.mlkit.nl.translate.internal.zzz.then(Unknown Source:4)
04-01 15:01:35.934 11691 11691 E AndroidRuntime: 	at com.google.android.gms.tasks.zze.run(com.google.android.gms:play-services-tasks@@17.1.0:5)
04-01 15:01:35.934 11691 11691 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
04-01 15:01:35.934 11691 11691 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-01 15:01:35.934 11691 11691 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:201)
04-01 15:01:35.934 11691 11691 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by sheepmaster** [comment]
Deobfuscated stack trace is (visible Google-internally) at https://paste.googleplex.com/4947974569328640.

Sadly, the exception message doesn't actually include the offending model name. @tmxdyf, do you happen to know which language model(s) you are using when the exception occurs?

**Comment by chrisito** [comment]
@tmxdyf circling back, can you clarify which language model you are using in the Translation? Thanks
