### ISSUE TITLE
Detect faces: Invalid rotation

### ISSUE THREAD

**Issue by ZacharyTech** [googlesamples/mlkit#268]
**version**
16.0.5、16.0.6

**issue**
Upgrade the SDK version to 16.0.5, the face cannot be detected correctly, and fall back to 16.0.2 to get the correct result.

**log**

```
 com.google.mlkit.common.MlKitException: Internal error has occurred when executing ML Kit tasks
        at com.google.mlkit.common.sdkinternal.ModelResource.zza(Unknown Source:64)
        at com.google.mlkit.common.sdkinternal.zzn.run(Unknown Source:10)
        at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@17.1.1:2)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@17.1.1:4)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(Unknown Source:8)
        at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(Unknown Source:10)
        at com.google.mlkit.common.sdkinternal.zzk.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.IllegalArgumentException: Invalid rotation: 3
        at com.google.mlkit.vision.common.internal.CommonConvertUtils.convertToMVRotation(com.google.mlkit:vision-common@@16.3.0:1)
        at com.google.mlkit.vision.face.internal.zza.zzh(com.google.android.gms:play-services-mlkit-face-detection@@16.1.5:12)
        at com.google.mlkit.vision.face.internal.zza.zzb(com.google.android.gms:play-services-mlkit-face-detection@@16.1.5:2)
        at com.google.mlkit.vision.face.internal.zzh.zzc(com.google.android.gms:play-services-mlkit-face-detection@@16.1.5:3)
        at com.google.mlkit.vision.face.internal.zzh.run(com.google.android.gms:play-services-mlkit-face-detection@@16.1.5:1)
        at com.google.mlkit.vision.common.internal.MobileVisionBase.zza(Unknown Source:2)
        at com.google.mlkit.vision.common.internal.zzc.call(Unknown Source:4)
        at com.google.mlkit.common.sdkinternal.ModelResource.zza(Unknown Source:37)
        at com.google.mlkit.common.sdkinternal.zzn.run(Unknown Source:10) 
        at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@17.1.1:2) 
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@17.1.1:4) 
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(Unknown Source:8) 
        at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(Unknown Source:10) 
        at com.google.mlkit.common.sdkinternal.zzk.run(Unknown Source:2) 
        at java.lang.Thread.run(Thread.java:923) 
```

**Code**

```java
 FaceDetectorOptions realTimeOpts =
                new FaceDetectorOptions.Builder()
                        .setLandmarkMode(FaceDetectorOptions.LANDMARK_MODE_NONE)
                        .setPerformanceMode(FaceDetectorOptions.PERFORMANCE_MODE_FAST)
                        .enableTracking()
                        .build();

InputImage image = InputImage.fromBitmap(bitmap, 270);
FaceDetector faceDetector = FaceDetection.getClient(realTimeOpts);
faceDetector.process(image)
                .addOnSuccessListener(
                        faces -> {
                          //  detected face
                        })
                .addOnFailureListener(
                        e -> {
                            // error
                        });

```

**Comment by cs-googler** [comment]
Thanks for reporting! We will fix this and publish the fix in the next release.

**Comment by cs-googler** [comment]
Hi this should have been fixed with the latest release. Closing
