### ISSUE TITLE
Proguard Issue of using ML Kit custom model

### ISSUE THREAD

**Issue by chihweil5** [googlesamples/mlkit#30]
### Step 1: Describe your environment

  * Android device: Pixel3
  * Android OS version: Android 10
  * Google Play Services version: 17
  * Firebase/Play Services SDK version: 17
  
### Step 2: Describe the problem:
I would like to use Firebase ML Kit custom models, and run into a proguard obfuscating issue when initializing `FirebaseModelInterpreter`. Any groguard guideline/example would be appreciated.

I have added these rules
```
-keepnames class com.google.firebase.** { *; }
-keepnames class com.google.android.gms.** { *; }
```

#### Steps to reproduce:

In build.gradle, set `minifyEnabled true` to enable Proguard
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.

The crash log
```
java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String r.c.a.e.b() (tried Java_r_c_a_e_b and Java_r_c_a_e_b__)
    at r.c.a.e.b(Native Method)
    at com.google.android.gms.internal.firebase_ml.zzpe.<clinit>(SourceFile:1)
    at com.google.firebase.ml.custom.FirebaseModelInterpreter.<init>(SourceFile:16)
    at com.google.firebase.ml.custom.FirebaseModelInterpreter.zza(SourceFile:6)
    at com.google.firebase.ml.custom.FirebaseModelInterpreter.getInstance(SourceFile:1)
```
  
#### Expected Results:

  * What did you expect to happen?
  
When I added `-dontobfuscate` to my proguard rules, the initialization works. 

#### Relevant Code:

```
import com.google.android.gms.tasks.Task
import com.google.android.gms.tasks.Tasks
import com.google.firebase.ml.common.FirebaseMLException
import com.google.firebase.ml.common.modeldownload.FirebaseLocalModel
import com.google.firebase.ml.common.modeldownload.FirebaseModelManager
import com.google.firebase.ml.custom.FirebaseModelDataType
import com.google.firebase.ml.custom.FirebaseModelInputOutputOptions
import com.google.firebase.ml.custom.FirebaseModelInputs
import com.google.firebase.ml.custom.FirebaseModelInterpreter
import com.google.firebase.ml.custom.FirebaseModelOptions

fun init(context: Context) {
    val modelOptions = FirebaseModelOptions.Builder()
        .setLocalModelName("mobilenet_v2_1.0_224_quant")
        .build()

    val localModelSource = FirebaseLocalModel.Builder(MODEL_NAME).setAssetFilePath("mobilenet_v2_1.0_224_quant.tflite").build()

    val firebaseModelManager = FirebaseModelManager.getInstance().apply {
        registerLocalModel(localModelSource)
    }

    interpreter = FirebaseModelInterpreter.getInstance(modelOptions)
    labelList = loadLabelList(context.applicationContext)

    val inputDims = intArrayOf(DIM_BATCH_SIZE, DIM_IMG_SIZE, DIM_IMG_SIZE, DIM_PIXEL_SIZE)
    val outputDims = intArrayOf(1, labelList.size)

    val dataType = FirebaseModelDataType.BYTE

    dataOptions = FirebaseModelInputOutputOptions.Builder()
        .setInputFormat(0, dataType, inputDims)
        .setOutputFormat(0, dataType, outputDims)
        .build()
}
```

**Comment by mehdi-salehi** [comment]
after shrinking by proguard:


W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.mlkit.vision.barcode.internal.BarcodeScannerImpl com.google.mlkit.vision.barcode.internal.BarcodeScannerImpl$zza.zza(com.google.mlkit.vision.barcode.BarcodeScannerOptions)' on a null object reference
W/System.err:     at com.google.mlkit.vision.barcode.BarcodeScanning.getClient(SourceFile:3)
W/System.err:     at com.mrb.cameradetectorlib.DetectorViewModel.barcodeDetector(SourceFile:90)
W/System.err:     at com.mrb.cameradetectorlib.DetectorViewModel$processImage$1.invokeSuspend(SourceFile:42)
W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
W/System.err:     at kotlinx.coroutines.DispatchedTask.run(SourceFile:56)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:571)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(SourceFile:738)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(SourceFile:678)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:665)

**Comment by mehdi-salehi** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process:  PID: 20168
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tse.myapplication2.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.mlkit.vision.barcode.internal.BarcodeScannerImpl com.google.mlkit.vision.barcode.internal.zzd.zza()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3319)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
        at android.app.ActivityThread.access$1100(ActivityThread.java:229)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7406)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.mlkit.vision.barcode.internal.BarcodeScannerImpl com.google.mlkit.vision.barcode.internal.zzd.zza()' on a null object reference
        at com.google.mlkit.vision.barcode.BarcodeScanning.getClient(SourceFile:1)
        at com.tse.myapplication2.MainActivity.onCreate(SourceFile:45)
        at android.app.Activity.performCreate(Activity.java:6904)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:7406) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
