### ISSUE TITLE
Waiting for the face detection module to be downloaded. Please wait.

### ISSUE THREAD

**Issue by MyRui** [googlesamples/mlkit#308]
When For bundling the model in my app:
dependencies {
      // Use this dependency to bundle the model with your app
      implementation 'com.google.mlkit:face-detection:16.1.0'
    }
}
I don't need download mode from google play store,need Model  statically linked to my app at build time.
But now, when install app from android studio ,it still need to download the face mode?  My app show the error : "Waiting for the face detection module to be downloaded. Please wait."

The trace:
2021-05-28 11:05:15.554 22381-22381/com.dr.hello.facecheckdemo W/System.err: com.google.mlkit.common.MlKitException: Waiting for the face detection module to be downloaded. Please wait.
2021-05-28 11:05:15.554 22381-22381/com.dr.hello.facecheckdemo W/System.err:     at com.google.mlkit.vision.face.internal.zza.zzb(com.google.android.gms:play-services-mlkit-face-detection@@16.1.6:8)
2021-05-28 11:05:15.555 22381-22381/com.dr.hello.facecheckdemo W/System.err:     at com.google.mlkit.vision.face.internal.zzh.zzc(com.google.android.gms:play-services-mlkit-face-detection@@16.1.6:3)
2021-05-28 11:05:15.555 22381-22381/com.dr.hello.facecheckdemo W/System.err:     at com.google.mlkit.vision.face.internal.zzh.run(com.google.android.gms:play-services-mlkit-face-detection@@16.1.6:1)
2021-05-28 11:05:15.555 22381-22381/com.dr.hello.facecheckdemo W/System.err:     at com.google.mlkit.vision.common.internal.MobileVisionBase.zza(Unknown Source:2)
2021-05-28 11:05:15.555 22381-22381/com.dr.hello.facecheckdemo W/System.err:     at com.google.mlkit.vision.common.internal.zzc.call(Unknown Source:4)
2021-05-28 11:05:15.555 22381-22381/com.dr.hello.facecheckdemo W/System.err:     at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@17.2.0:8)
2021-05-28 11:05:15.555 22381-22381/com.dr.hello.facecheckdemo W/System.err:     at com.google.mlkit.common.sdkinternal.zzm.run(Unknown Source:10)
2021-05-28 11:05:15.555 22381-22381/com.dr.hello.facecheckdemo W/System.err:     at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@17.2.0:2)
2021-05-28 11:05:15.555 22381-22381/com.dr.hello.facecheckdemo W/System.err:     at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@17.2.0:4)
2021-05-28 11:05:15.555 22381-22381/com.dr.hello.facecheckdemo W/System.err:     at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@17.2.0:1)
2021-05-28 11:05:15.555 22381-22381/com.dr.hello.facecheckdemo W/System.err:     at com.google.mlkit.common.sdkinternal.zzi.run(Unknown Source:2)
2021-05-28 11:05:15.555 22381-22381/com.dr.hello.facecheckdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-05-28 11:05:15.555 22381-22381/com.dr.hello.facecheckdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-05-28 11:05:15.555 22381-22381/com.dr.hello.facecheckdemo W/System.err:     at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@17.2.0:2)
2021-05-28 11:05:15.555 22381-22381/com.dr.hello.facecheckdemo W/System.err:     at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2)
2021-05-28 11:05:15.555 22381-22381/com.dr.hello.facecheckdemo W/System.err:     at java.lang.Thread.run(Thread.java:923)

**Comment by MyRui** [comment]
Thanks, previous version 'com.google.mlkit:face-detection:16.0.7'  is ok

**Comment by zhouyiself** [comment]
We just released com.google.mlkit:face-detection:16.1.1, please help verify.

**Comment by zhouyiself** [comment]
Please reopen the issue if it's not resolved with the latest version.

**Comment by MyRui** [comment]
thanks, com.google.mlkit:face-detection:16.1.1 is ok.

**Comment by rohilla17** [comment]
Facing download issue again in 17.0.1

**Comment by rohilla17** [comment]
when we hard reset the phone, the ml kit 17.0.1 is not downloading in any case

**Comment by jackqdyulei** [comment]
Hi rohilla17, do you still have issue? If so, please provide following info so we can take a further look.
- device info
- gmscore version

Please noted current face module is large so it takes time to download.

**Comment by egbuna** [comment]
Facing same issue @jackqdyulei 

device info
Brand:samsung
Model:Galaxy A8+(2018)

Operating system
Version:Android 9

Rooted:No

**Comment by alizarei95** [comment]
Problem still exists in v17.1.0 but I could fix it by clearing all data of Google Play Services
