### ISSUE TITLE
Qr code recognition null array

### ISSUE THREAD

**Issue by AEfremov** [googlesamples/mlkit#326]
Hello all! I am trying to recognize qr code from arscene and getting

`Caused by: java.lang.NullPointerException: Attempt to get length of null array`

What is null array? There r bitmap troubles?

```
override fun onUpdate(frameTime: FrameTime?) {
        if (session == null) {
            return
        }

        val frame: Frame = _binding.arSceneView.arFrame ?: return

        val cameraImage = frame.tryAcquireCameraImage()
        if (cameraImage != null) {
            Log.d("cameraImage", "${cameraImage.height} ${cameraImage.width} ${cameraImage.timestamp}")

            if (cameraImage.format != ImageFormat.YUV_420_888) {
                throw IllegalArgumentException(
                    "Expected image in YUV_420_888 format, got format " + cameraImage.format
                )
            }
            
            val processedImageBytesGrayscale: ByteBuffer =
                edgeDetector.detect(
                    cameraImage.width,
                    cameraImage.height,
                    cameraImage.planes[0].rowStride,
                    cameraImage.planes[0].buffer
                )

            val bitmap = Bitmap.createBitmap(
                cameraImage.width,
                cameraImage.height,
                Bitmap.Config.ALPHA_8
            )
            processedImageBytesGrayscale.rewind()
            bitmap.copyPixelsFromBuffer(processedImageBytesGrayscale)

            cameraId = session?.cameraConfig?.cameraId!!
            val rotationDegrees = displayRotationHelper?.getCameraSensorToDisplayRotation(cameraId)
            val visionImage = InputImage.fromBitmap(bitmap, rotationDegrees!!)
            val scanner = BarcodeScanning.getClient(options)

            scanner.process(visionImage)
                .addOnSuccessListener { barcodes ->
                    Log.d("addOnSuccessListener", barcodes.toString())
                }
                .addOnFailureListener {
                    it.printStackTrace()
                    Log.d("addOnFailureListener", it.message.toString())
                }
                .addOnCanceledListener {
                    Log.d("addOnCanceledListener", "cancel")
                }
                .addOnCompleteListener {
                    Log.d("addOnCompleteListener", it.toString())
                    cameraImage.close()
                }
        }
    }
```

Thanks!

**Comment by zhouyiself** [comment]
Have you verified the passed in Bitmap has valid data?

**Comment by AEfremov** [comment]
@zhouyiself after bitmap.copyPixelsFromBuffer(processedImageBytesGrayscale) see bitmap on screenshot. Do you mean to verify data programmatically?

<img width="413" alt="photo_2021-07-20_23-07-44 jpg 2021-07-20 23-08-08" src="https://user-images.githubusercontent.com/11681110/126388824-5d76bb43-03c3-43a0-aaab-3c01d1e8b488.png">

**Comment by zhouyiself** [comment]
Thanks for sharing the test image.

Is the crash from "Log.d("addOnSuccessListener", barcodes.toString())" where you call #toString on a List?

**Comment by AEfremov** [comment]
@zhouyiself exception from 

```
.addOnFailureListener {
           it.printStackTrace()
          Log.d("addOnFailureListener", it.message.toString())
}
```
                
Full stacktrace of error.

```
com.google.mlkit.common.MlKitException: Internal error has occurred when executing ML Kit tasks
    at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@17.2.0:9)
    at com.google.mlkit.common.sdkinternal.zzm.run(Unknown Source:10)
    at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@17.2.0:2)
    at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@17.2.0:4)
    at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@17.2.0:1)
    at com.google.mlkit.common.sdkinternal.zzi.run(Unknown Source:2)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@17.2.0:2)
    at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2)
    at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.NullPointerException: Attempt to get length of null array
    at com.google.mlkit.vision.barcode.bundled.internal.zza.zzb(com.google.mlkit:barcode-scanning@@16.2.0:10)
    at com.google.android.gms.internal.mlkit_vision_barcode_bundled.zzaa.zza(com.google.mlkit:barcode-scanning@@16.2.0:3)
    at com.google.android.gms.internal.mlkit_vision_barcode_bundled.zzb.onTransact(com.google.mlkit:barcode-scanning@@16.2.0:3)
    at android.os.Binder.transact(Binder.java:1079)
    at com.google.android.gms.internal.mlkit_vision_barcode.zza.zzb(com.google.android.gms:play-services-mlkit-barcode-scanning@@16.2.0:2)
    at com.google.android.gms.internal.mlkit_vision_barcode.zzmz.zzd(com.google.android.gms:play-services-mlkit-barcode-scanning@@16.2.0:4)
    at com.google.mlkit.vision.barcode.internal.zzm.zza(com.google.android.gms:play-services-mlkit-barcode-scanning@@16.2.0:14)
    at com.google.mlkit.vision.barcode.internal.zzi.zzc(com.google.android.gms:play-services-mlkit-barcode-scanning@@16.2.0:3)
    at com.google.mlkit.vision.barcode.internal.zzi.run(com.google.android.gms:play-services-mlkit-barcode-scanning@@16.2.0:1)
    at com.google.mlkit.vision.common.internal.MobileVisionBase.zza(com.google.mlkit:vision-common@@16.5.0:2)
    at com.google.mlkit.vision.common.internal.zzd.call(Unknown Source:4)
    at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@17.2.0:8)
... 10 more
```

**Comment by zhouyiself** [comment]
I think it's due to the incompatible bitmap config.

Current internal barcode pipeline only supports ARGB_8888 config while your case is ALPHA_8. Can you try using that config and see if it works?

**Comment by AEfremov** [comment]
@zhouyiself using of extension gave me no errors but empty array [] from qr code

```
fun Image.toBitmap(): Bitmap {
        val yBuffer = planes[0].buffer // Y
        val vuBuffer = planes[2].buffer // VU

        val ySize = yBuffer.remaining()
        val vuSize = vuBuffer.remaining()

        val nv21 = ByteArray(ySize + vuSize)

        yBuffer.get(nv21, 0, ySize)
        vuBuffer.get(nv21, ySize, vuSize)

        val yuvImage = YuvImage(nv21, NV21, this.width, this.height, null)
        val out = ByteArrayOutputStream()
        yuvImage.compressToJpeg(Rect(0, 0, yuvImage.width, yuvImage.height), 50, out)
        val imageBytes = out.toByteArray()
        return BitmapFactory.decodeByteArray(imageBytes, 0, imageBytes.size)
    }
```

<img width="387" alt="photo_2021-07-21_16-57-11 jpg 2021-07-21 16-57-45" src="https://user-images.githubusercontent.com/11681110/126501318-877888fc-9bc7-4af0-8be6-3ec845d8c068.png">

**Comment by AEfremov** [comment]
it was bitmap problem. New extension function helps me. @zhouyiself thanks for help.

```
fun Image.toBitmapExtended(): Bitmap {
        val planes: Array<Image.Plane> = planes
        val yBuffer = planes[0].buffer
        val uBuffer = planes[1].buffer
        val vBuffer = planes[2].buffer

        val ySize = yBuffer.remaining()
        val uSize = uBuffer.remaining()
        val vSize = vBuffer.remaining()

        val nv21 = ByteArray(ySize + uSize + vSize)
        // U and V are swapped
        yBuffer.get(nv21, 0, ySize)
        vBuffer.get(nv21, ySize, vSize)
        uBuffer.get(nv21, ySize + vSize, uSize)

        val yuvImage = YuvImage(nv21, NV21, width, height, null)
        val out = ByteArrayOutputStream()
        yuvImage.compressToJpeg(Rect(0, 0, yuvImage.width, yuvImage.height), 75, out)

        val imageBytes = out.toByteArray()

        return BitmapFactory.decodeByteArray(imageBytes, 0, imageBytes.size)
    }
```
