### ISSUE TITLE
Ml Kit Image labeller issue

### ISSUE THREAD

**Issue by ansh2166** [googlesamples/mlkit#399]
Can anyone help me in my problem?

Issue I face:
![image](https://user-images.githubusercontent.com/72782632/143683829-a8b7899f-9cfa-4a07-9be7-4cbbe6d0fd5d.png)

```
11-27 13:39:50.807 W/System.err(10572): java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.mlkit.vision.common.internal.MobileVisionBase com.google.mlkit.vision.common.internal.MultiFlavorDetectorCreator.create(com.google.mlkit.vision.common.internal.MultiFlavorDetectorCreator$DetectorOptions)' on a null object reference
11-27 13:39:50.807 W/System.err(10572): 	at com.google.mlkit.vision.label.internal.ImageLabelerImpl.<init>(com.google.mlkit:image-labeling-common@@17.1.0:1)
11-27 13:39:50.807 W/System.err(10572): 	at com.google.mlkit.vision.label.internal.ImageLabelerImpl.zza(com.google.mlkit:image-labeling-common@@17.1.0:2)
11-27 13:39:50.807 W/System.err(10572): 	at com.google.mlkit.vision.label.ImageLabeling.getClient(com.google.mlkit:image-labeling-common@@17.1.0:2)
11-27 13:39:50.807 W/System.err(10572): 	at com.kabby.mlkitlabeller.MlKitLabeller.GetLabel(MlKitLabeller.java:50)
11-27 13:39:50.807 W/System.err(10572): 	at java.lang.reflect.Method.invoke(Native Method)
11-27 13:39:50.807 W/System.err(10572): 	at gnu.expr.PrimProcedure.apply(PrimProcedure.java:285)
11-27 13:39:50.807 W/System.err(10572): 	at gnu.mapping.CallContext.runUntilDone(CallContext.java:234)
11-27 13:39:50.807 W/System.err(10572): 	at gnu.mapping.CallContext.runUntilValue(CallContext.java:298)
11-27 13:39:50.807 W/System.err(10572): 	at gnu.mapping.MethodProc.applyN(MethodProc.java:113)
11-27 13:39:50.807 W/System.err(10572): 	at gnu.kawa.reflect.Invoke.applyN(Invoke.java:193)
11-27 13:39:50.807 W/System.err(10572): 	at gnu.kawa.functions.ApplyToArgs.applyN(ApplyToArgs.java:139)
11-27 13:39:50.807 W/System.err(10572): 	at gnu.kawa.functions.Apply.applyN(Apply.java:70)
11-27 13:39:50.807 W/System.err(10572): 	at gnu.mapping.ProcedureN.apply2(ProcedureN.java:39)
11-27 13:39:50.807 W/System.err(10572): 	at com.google.youngandroid.runtime.callComponentMethod(runtime5622752338898401648.scm:1043)
11-27 13:39:50.807 W/System.err(10572): 	at io.kodular.rudrasoftwarecorporation.owowao.Screen1.Button2$Click(Screen1.yail:32)
11-27 13:39:50.807 W/System.err(10572): 	at io.kodular.rudrasoftwarecorporation.owowao.Screen1$frame.apply0(Screen1.yail:523)
11-27 13:39:50.807 W/System.err(10572): 	at gnu.expr.ModuleBody.applyN(ModuleBody.java:226)
11-27 13:39:50.807 W/System.err(10572): 	at gnu.expr.ModuleMethod.applyN(ModuleMethod.java:216)
11-27 13:39:50.807 W/System.err(10572): 	at gnu.kawa.functions.ApplyToArgs.applyN(ApplyToArgs.java:139)
11-27 13:39:50.807 W/System.err(10572): 	at gnu.kawa.functions.Apply.applyN(Apply.java:70)
11-27 13:39:50.807 W/System.err(10572): 	at gnu.mapping.ProcedureN.apply2(ProcedureN.java:39)
11-27 13:39:50.807 W/System.err(10572): 	at io.kodular.rudrasoftwarecorporation.owowao.Screen1.dispatchEvent(Screen1.yail:10125)
11-27 13:39:50.807 W/System.err(10572): 	at com.google.appinventor.components.runtime.EventDispatcher.hxYOFxFjLpN1maJuWNxUV40nExCGxsxkDPOTgtzMu4zlZCQb3bPlKsXo1SYJg6ME(SourceFile:243)
11-27 13:39:50.807 W/System.err(10572): 	at com.google.appinventor.components.runtime.EventDispatcher.dispatchEvent(SourceFile:199)
11-27 13:39:50.807 W/System.err(10572): 	at com.google.appinventor.components.runtime.Button.Click(SourceFile:54)
11-27 13:39:50.807 W/System.err(10572): 	at com.google.appinventor.components.runtime.Button.click(SourceFile:45)
11-27 13:39:50.808 W/System.err(10572): 	at com.google.appinventor.components.runtime.ButtonBase.onClick(SourceFile:673)
11-27 13:39:50.808 W/System.err(10572): 	at android.view.View.performClick(View.java:6597)
11-27 13:39:50.808 W/System.err(10572): 	at android.view.View.performClickInternal(View.java:6574)
11-27 13:39:50.808 W/System.err(10572): 	at android.view.View.access$3100(View.java:778)
11-27 13:39:50.808 W/System.err(10572): 	at android.view.View$PerformClick.run(View.java:25885)
11-27 13:39:50.808 W/System.err(10572): 	at android.os.Handler.handleCallback(Handler.java:873)
11-27 13:39:50.808 W/System.err(10572): 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-27 13:39:50.808 W/System.err(10572): 	at android.os.Looper.loop(Looper.java:193)
11-27 13:39:50.808 W/System.err(10572): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
11-27 13:39:50.808 W/System.err(10572): 	at java.lang.reflect.Method.invoke(Native Method)
11-27 13:39:50.808 W/System.err(10572): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
11-27 13:39:50.808 W/System.err(10572): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by ansh2166** [comment]
Okay, I somehow fixed it but now this comes :(

![image](https://user-images.githubusercontent.com/72782632/143778293-f4d6face-7a0d-40c2-b749-7906cac22ca6.png)

```
11-28 16:57:27.296 W/System.err( 5130): java.lang.NullPointerException: null reference
11-28 16:57:27.297 W/System.err( 5130): 	at com.google.android.gms.common.internal.Preconditions.checkNotNull(com.google.android.gms:play-services-basement@@17.6.0:1)
11-28 16:57:27.297 W/System.err( 5130): 	at com.google.mlkit.vision.common.internal.MultiFlavorDetectorCreator.create(com.google.mlkit:vision-common@@16.6.0:1)
11-28 16:57:27.297 W/System.err( 5130): 	at com.google.mlkit.vision.label.internal.ImageLabelerImpl.<init>(com.google.mlkit:image-labeling-common@@17.1.0:1)
11-28 16:57:27.297 W/System.err( 5130): 	at com.google.mlkit.vision.label.internal.ImageLabelerImpl.zza(com.google.mlkit:image-labeling-common@@17.1.0:2)
11-28 16:57:27.297 W/System.err( 5130): 	at com.google.mlkit.vision.label.ImageLabeling.getClient(com.google.mlkit:image-labeling-common@@17.1.0:2)
11-28 16:57:27.297 W/System.err( 5130): 	at com.kabby.mlk.mlkitlabelling.MLKitLabelling.GetLabel(MLKitLabelling.java:54)
11-28 16:57:27.297 W/System.err( 5130): 	at java.lang.reflect.Method.invoke(Native Method)
11-28 16:57:27.297 W/System.err( 5130): 	at gnu.expr.PrimProcedure.apply(PrimProcedure.java:285)
11-28 16:57:27.297 W/System.err( 5130): 	at gnu.mapping.CallContext.runUntilDone(CallContext.java:234)
11-28 16:57:27.297 W/System.err( 5130): 	at gnu.mapping.CallContext.runUntilValue(CallContext.java:298)
11-28 16:57:27.297 W/System.err( 5130): 	at gnu.mapping.MethodProc.applyN(MethodProc.java:113)
11-28 16:57:27.297 W/System.err( 5130): 	at gnu.kawa.reflect.Invoke.applyN(Invoke.java:193)
11-28 16:57:27.297 W/System.err( 5130): 	at gnu.kawa.functions.ApplyToArgs.applyN(ApplyToArgs.java:139)
11-28 16:57:27.297 W/System.err( 5130): 	at gnu.kawa.functions.Apply.applyN(Apply.java:70)
11-28 16:57:27.297 W/System.err( 5130): 	at gnu.mapping.ProcedureN.apply2(ProcedureN.java:39)
11-28 16:57:27.297 W/System.err( 5130): 	at com.google.youngandroid.runtime.callComponentMethod(runtime3163500755750213266.scm:1043)
11-28 16:57:27.297 W/System.err( 5130): 	at io.kodular.rudrasoftwarecorporation.owowao.Screen1.Button2$Click(Screen1.yail:34)
11-28 16:57:27.297 W/System.err( 5130): 	at io.kodular.rudrasoftwarecorporation.owowao.Screen1$frame.apply0(Screen1.yail:523)
11-28 16:57:27.297 W/System.err( 5130): 	at gnu.expr.ModuleBody.applyN(ModuleBody.java:226)
11-28 16:57:27.297 W/System.err( 5130): 	at gnu.expr.ModuleMethod.applyN(ModuleMethod.java:216)
11-28 16:57:27.297 W/System.err( 5130): 	at gnu.kawa.functions.ApplyToArgs.applyN(ApplyToArgs.java:139)
11-28 16:57:27.297 W/System.err( 5130): 	at gnu.kawa.functions.Apply.applyN(Apply.java:70)
11-28 16:57:27.297 W/System.err( 5130): 	at gnu.mapping.ProcedureN.apply2(ProcedureN.java:39)
11-28 16:57:27.297 W/System.err( 5130): 	at io.kodular.rudrasoftwarecorporation.owowao.Screen1.dispatchEvent(Screen1.yail:10125)
11-28 16:57:27.297 W/System.err( 5130): 	at com.google.appinventor.components.runtime.EventDispatcher.hxYOFxFjLpN1maJuWNxUV40nExCGxsxkDPOTgtzMu4zlZCQb3bPlKsXo1SYJg6ME(SourceFile:243)
11-28 16:57:27.297 W/System.err( 5130): 	at com.google.appinventor.components.runtime.EventDispatcher.dispatchEvent(SourceFile:199)
11-28 16:57:27.297 W/System.err( 5130): 	at com.google.appinventor.components.runtime.Button.Click(SourceFile:54)
11-28 16:57:27.297 W/System.err( 5130): 	at com.google.appinventor.components.runtime.Button.click(SourceFile:45)
11-28 16:57:27.297 W/System.err( 5130): 	at com.google.appinventor.components.runtime.ButtonBase.onClick(SourceFile:673)
11-28 16:57:27.297 W/System.err( 5130): 	at android.view.View.performClick(View.java:6597)
11-28 16:57:27.297 W/System.err( 5130): 	at android.view.View.performClickInternal(View.java:6574)
11-28 16:57:27.297 W/System.err( 5130): 	at android.view.View.access$3100(View.java:778)
11-28 16:57:27.297 W/System.err( 5130): 	at android.view.View$PerformClick.run(View.java:25885)
11-28 16:57:27.297 W/System.err( 5130): 	at android.os.Handler.handleCallback(Handler.java:873)
11-28 16:57:27.297 W/System.err( 5130): 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-28 16:57:27.297 W/System.err( 5130): 	at android.os.Looper.loop(Looper.java:193)
11-28 16:57:27.297 W/System.err( 5130): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
11-28 16:57:27.297 W/System.err( 5130): 	at java.lang.reflect.Method.invoke(Native Method)
11-28 16:57:27.297 W/System.err( 5130): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
11-28 16:57:27.297 W/System.err( 5130): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
11-28 16:57:27.300 I/RuntimeErrorAlert( 5130): in alert
```

**Comment by SilverDestiny** [comment]
Hi,

Could you provide more info about this issue, i.e. SDK and version you used, Android API, etc.

It'd be the best if you can provide the the steps to consistently repro this error. Thanks!

**Comment by ansh2166** [comment]
> 

I used all required jars and used same code as present in examples, but still Null pointer exception comes

**Comment by SilverDestiny** [comment]
Which example? Do you have the link to the example you used?

ML Kit has examples at https://github.com/googlesamples/mlkit

For Vision features, https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart is the vision quickstart app.

**Comment by SilverDestiny** [comment]
Close this issue as no recent update.
Feel free to reopen it if you need any follow-up :)
