### ISSUE TITLE
Custom Object detection

### ISSUE THREAD

**Issue by BeshoyAdelHemaya** [googlesamples/mlkit#402]
We created a dataset using Object detection. After the training, we downloaded model.tflite and added it to assets folder. Every time we ran the demo, we got the following logs:

 6921 calculator_graph.cc:810] INVALID_ARGUMENT: CalculatorGraph::Run() failed in Run: 
    Calculator::Open() for node "BoxClassifierCalculator" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1). [type.googleapis.com/mediapipe.StatusList='\n\xf5\x01\x08\x03\x12\xc3\x01\x43\x61lculator::Open() for node \"BoxClassifierCalculator\" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).\x1a+\n$tflite::support::TfLiteSupportStatus\x12\x03\x34\x30\x30']
    === Source Location Trace: === 
    third_party/mediapipe/framework/tool/status_util.cc:139
2021-11-30 14:35:15.326 6461-6921/com.google.mlkit.vision.demo E/native: E1130 14:35:15.326678    6921 pipeline_jni.cc:100] INVALID_ARGUMENT: CalculatorGraph::Run() failed in Run: 
    Calculator::Open() for node "BoxClassifierCalculator" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1). [type.googleapis.com/mediapipe.StatusList='\n\xf5\x01\x08\x03\x12\xc3\x01\x43\x61lculator::Open() for node \"BoxClassifierCalculator\" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).\x1a+\n$tflite::support::TfLiteSupportStatus\x12\x03\x34\x30\x30']
    === Source Location Trace: === 
    third_party/mediapipe/framework/tool/status_util.cc:139
    photos/vision/visionkit/pipeline/pipeline.cc:117
2021-11-30 14:35:15.326 6461-6921/com.google.mlkit.vision.demo E/native: E1130 14:35:15.326973    6921 pipeline_jni.cc:270] INVALID_ARGUMENT: Graph has errors: 
    Calculator::Open() for node "BoxClassifierCalculator" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1). [type.googleapis.com/mediapipe.StatusList='\n\xf5\x01\x08\x03\x12\xc3\x01\x43\x61lculator::Open() for node \"BoxClassifierCalculator\" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).\x1a+\n$tflite::support::TfLiteSupportStatus\x12\x03\x34\x30\x30']
    === Source Location Trace: === 
    third_party/mediapipe/framework/tool/status_util.cc:139
    photos/vision/visionkit/pipeline/scheduler.cc:1114
    photos/vision/visionkit/pipeline/pipeline.cc:109
2021-11-30 14:35:15.327 6461-6921/com.google.mlkit.vision.demo E/native: E1130 14:35:15.327257    6921 pipeline_jni.cc:270] INVALID_ARGUMENT: Graph has errors: 
    Calculator::Open() for node "BoxClassifierCalculator" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1). [type.googleapis.com/mediapipe.StatusList='\n\xf5\x01\x08\x03\x12\xc3\x01\x43\x61lculator::Open() for node \"BoxClassifierCalculator\" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).\x1a+\n$tflite::support::TfLiteSupportStatus\x12\x03\x34\x30\x30']
    === Source Location Trace: === 
    third_party/mediapipe/framework/tool/status_util.cc:139
    photos/vision/visionkit/pipeline/scheduler.cc:1114
    photos/vision/visionkit/pipeline/pipeline.cc:109
2021-11-30 14:35:15.331 6461-6772/com.google.mlkit.vision.demo D/TransportRuntime.SQLiteEventStore: Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
2021-11-30 14:35:15.332 6461-6461/com.google.mlkit.vision.demo D/VisionProcessorBase: Failed to process. Error: Failed to initialize detector. Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).
2021-11-30 14:35:15.332 6461-6461/com.google.mlkit.vision.demo W/System.err: com.google.mlkit.common.MlKitException: Failed to initialize detector. Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).
2021-11-30 14:35:15.332 6461-6461/com.google.mlkit.vision.demo W/System.err:     at com.google.mlkit.vision.vkp.PipelineManager.start(com.google.mlkit:vision-internal-vkp@@18.2.0:73)
2021-11-30 14:35:15.332 6461-6461/com.google.mlkit.vision.demo W/System.err:     at com.google.mlkit.vision.objects.custom.internal.zze.tryLoad(com.google.mlkit:object-detection-custom@@16.3.3:3)
2021-11-30 14:35:15.332 6461-6461/com.google.mlkit.vision.demo W/System.err:     at com.google.mlkit.common.sdkinternal.model.CustomModelLoader.load(com.google.mlkit:common@@17.4.0:3)
2021-11-30 14:35:15.332 6461-6461/com.google.mlkit.vision.demo W/System.err:     at com.google.mlkit.vision.objects.custom.internal.zzf.load(com.google.mlkit:object-detection-custom@@16.3.3:2)
2021-11-30 14:35:15.332 6461-6461/com.google.mlkit.vision.demo W/System.err:     at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@17.4.0:4)
2021-11-30 14:35:15.332 6461-6461/com.google.mlkit.vision.demo W/System.err:     at com.google.mlkit.common.sdkinternal.zzm.run(Unknown Source:10)
2021-11-30 14:35:15.332 6461-6461/com.google.mlkit.vision.demo W/System.err:     at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@17.4.0:2)
2021-11-30 14:35:15.332 6461-6461/com.google.mlkit.vision.demo W/System.err:     at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@17.4.0:4)
2021-11-30 14:35:15.332 6461-6461/com.google.mlkit.vision.demo W/System.err:     at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@17.4.0:1)
2021-11-30 14:35:15.332 6461-6461/com.google.mlkit.vision.demo W/System.err:     at com.google.mlkit.common.sdkinternal.zzi.run(Unknown Source:2)
2021-11-30 14:35:15.332 6461-6461/com.google.mlkit.vision.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-11-30 14:35:15.332 6461-6461/com.google.mlkit.vision.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-11-30 14:35:15.332 6461-6461/com.google.mlkit.vision.demo W/System.err:     at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@17.4.0:2)
2021-11-30 14:35:15.332 6461-6461/com.google.mlkit.vision.demo W/System.err:     at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2)
2021-11-30 14:35:15.332 6461-6461/com.google.mlkit.vision.demo W/System.err:     at java.lang.Thread.run(Thread.java:929)
2021-11-30 14:35:15.332 6461-6461/com.google.mlkit.vision.demo E/ObjectDetectorProcessor: Object detection failed!
    com.google.mlkit.common.MlKitException: Failed to initialize detector. Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).
        at com.google.mlkit.vision.vkp.PipelineManager.start(com.google.mlkit:vision-internal-vkp@@18.2.0:73)
        at com.google.mlkit.vision.objects.custom.internal.zze.tryLoad(com.google.mlkit:object-detection-custom@@16.3.3:3)
        at com.google.mlkit.common.sdkinternal.model.CustomModelLoader.load(com.google.mlkit:common@@17.4.0:3)
        at com.google.mlkit.vision.objects.custom.internal.zzf.load(com.google.mlkit:object-detection-custom@@16.3.3:2)
        at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@17.4.0:4)
        at com.google.mlkit.common.sdkinternal.zzm.run(Unknown Source:10)
        at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@17.4.0:2)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@17.4.0:4)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@17.4.0:1)
        at com.google.mlkit.common.sdkinternal.zzi.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@17.4.0:2)
        at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:929)

**Comment by steven-chengji-yan** [comment]
Hi,

Please take a look at the custom model requirement here: https://developers.google.com/ml-kit/custom-models#model-compatibility

The Custom Object Detection accept a classification model with certain requirements shown in the doc above.

**Comment by plottsjp** [comment]
@steven-chengji-yan I know this probably a bit outside the scope of this issue but I (and @BeshoyAdelHemaya) could use some help in understanding these output requirements - or at how to train a tflite object recognition model the will conform to them.

"The model must have at least one output tensor with N classes and either 2 or 4 dimensions:
(1xN)
(1x1x1xN)"

So far i've trained a model with Vertex AI (autoML successor) and TensorFlow Lite Model Make and both of them came out with 3D outputs and don't understand how to make them conform to these requirements.

**Comment by steven-chengji-yan** [comment]
Hi plottsjp,

"... at how to train a tflite **object recognition model**..."
Based on the [requirements](https://developers.google.com/ml-kit/custom-models#model-compatibility), the custom model needs to be an "**image classification model**" instead of "object recognition model".   Not sure if this could help answer your question.

The ML Kit Object Detection API uses a two step pipeline: it first detects an object and then classify it. The custom model support allows the pipeline to use a custom image classification model for step2. 

I am not sure but I guess when you say "object recognition model" you mean an one-step object detection and recognition model (correct me if I am wrong). That is not supported at the moment.

Let me know if you have further questions.

**Comment by plottsjp** [comment]
@steven-chengji-yan Thank you for that clarification! I don't think i fully understood the limitation in the requirements when it said  "image classification model" or perhaps i glossed over it. 

Now that you've explained how ML Kit's object recognition works (the two step process) it is much easier to understand that "Both the Image Labeling and the Object Detection & Tracking API offer support for custom image classification models." does not actually mean i can use a custom one-step object detection and recognition model. But rather i can use a custom image classification model as a second step in a two step object recognition model.

**Comment by steven-chengji-yan** [comment]
Glad it helps.
