### ISSUE TITLE
[Bug report] Lots of ANRs from `CommonComponentRegistrar.getComponents`

### ISSUE THREAD

**Issue by Thomas-Vos** [googlesamples/mlkit#434]
**Describe the bug**
Issue was originally created at Firebase but they asked me to create it here: https://github.com/firebase/firebase-android-sdk/issues/3381

Getting lots of ANRs like this reported through Firebase Crashlytics:

Example stack trace (they are a bit different sometimes):
```
main (runnable): tid=1 systid=15779
       at com.google.mlkit.common.internal.CommonComponentRegistrar.getComponents(com.google.mlkit:common@@17.2.0:3)
       at com.google.firebase.components.ComponentRuntime.discoverComponents(ComponentRuntime.java:109)
       at com.google.firebase.components.ComponentRuntime.<init>(ComponentRuntime.java:91)
       at com.google.firebase.components.ComponentRuntime.<init>(ComponentRuntime.java:45)
       at com.google.firebase.components.ComponentRuntime$Builder.build(ComponentRuntime.java:360)
       at com.google.mlkit.common.sdkinternal.MlKitContext.zza(MlKitContext.java:9)
       at com.google.mlkit.common.internal.MlKitInitProvider.onCreate(com.google.mlkit:common@@17.2.0:3)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2516)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2486)
       at com.google.mlkit.common.internal.MlKitInitProvider.attachInfo(com.google.mlkit:common@@17.2.0:3)
       at android.app.ActivityThread.installProvider(ActivityThread.java:8198)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7704)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7458)
       at android.app.ActivityThread.access$1700(ActivityThread.java:310)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2283)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8641)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
```

Screenshot from last 90 days:
![Screenshot 2022-01-29 at 17 55 12](https://user-images.githubusercontent.com/11077217/151893017-d7ed775b-272a-4d6c-9f7a-f06d1bbb26d0.png)

I opened the ANR at the top with the most events:
![Screenshot 2022-01-29 at 17 55 51](https://user-images.githubusercontent.com/11077217/151893055-f2b4c3b1-5e26-4925-9bf0-cb77e88b984b.png) ![Screenshot 2022-01-29 at 17 56 08](https://user-images.githubusercontent.com/11077217/151893063-fbf9cd54-2f62-4505-bd48-a625f6961297.png) ![Screenshot 2022-01-29 at 17 58 47](https://user-images.githubusercontent.com/11077217/151893067-5f38dac5-b98b-4eaf-b407-4e27bd960ae6.png)

**To Reproduce**
No steps to reproduce as I am unable to do so myself.

**Expected behavior**
No ANR.

**SDK Info:**
com.google.android.gms:play-services-mlkit-barcode-scanning:16.2.0

**Smartphone:**
 - Device/Simulator: Mostly Samsung devices
 - Device/Simulator OS: Android 11 and Android 12

**Comment by jackqdyulei** [comment]
Thanks for your report. Currently I have no clue so just brainstorming.

1) Can you provide more stacktrace(e.g. other one or non-cropped one) which might provide more info
2) Can you check the device distribution of your user so we can know how many % uses samsung device(then compare with the current 99%)
3) Among the Samsung devices, do you know the device model info?(so we might know whether it happens mostly on low-end device)

**Comment by zhouyiself** [comment]
If it's mostly from App startup, then it might has something to do with the ML Kit auto-initialization via Content Provider which happens at startup time.

It's not a new change and should not take critical time, but there may be chance I guess that if your app recently does more stuff in the new release and then accumulating this ML Kit  initialization one might reach the ANR boundary on some devices?

To mitigate & verify this, you can remove the ML Kit auto-initialization and do it manually by this [MlKit#initialize](https://developers.google.com/android/reference/com/google/mlkit/common/MlKit#public-static-void-initialize-context-context) call. You can call this on either UI thread (after startup for sure) or background thread, but please make sure the call is finished before you create a BarcodeScanner instance.

**Comment by jackqdyulei** [comment]
Close because of inactivity
