### ISSUE TITLE
Crash when update androidx.camera:camera-view

### ISSUE THREAD

**Issue by DmitrSP** [googlesamples/mlkit#437]
When update androidx.camera:camera-view to v1.1.0-beta01 app crashes.

Logs:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.mlkit.vision.demo/com.google.mlkit.vision.demo.kotlin.CameraXLivePreviewActivity}: java.lang.IllegalStateException: CameraX is not configured properly. The most likely cause is you did not include a default implementation in your build such as 'camera-camera2'.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: CameraX is not configured properly. The most likely cause is you did not include a default implementation in your build such as 'camera-camera2'.
        at androidx.camera.core.CameraX.<init>(CameraX.java:109)
        at androidx.camera.lifecycle.ProcessCameraProvider.getOrCreateCameraXInstance(ProcessCameraProvider.java:181)
        at androidx.camera.lifecycle.ProcessCameraProvider.getInstance(ProcessCameraProvider.java:167)
        at com.google.mlkit.vision.demo.CameraXViewModel.getProcessCameraProvider(CameraXViewModel.java:51)
        at com.google.mlkit.vision.demo.kotlin.CameraXLivePreviewActivity.onCreate(CameraXLivePreviewActivity.kt:138)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by zhouyiself** [comment]
Looks androidx.camera:camera-view is not compatible with the old version of androidx.camera:camera-camera2.

Updating both to the latest version should resolve the crash issue.
https://developer.android.com/jetpack/androidx/releases/camera

**Comment by DmitrSP** [comment]
Yes, you're right. Stable release of androidx.camera:camera-camera2:1.0.2 is not compatible. Only v1.1.0-beta01. Thanks!
