### ISSUE TITLE
[Bug report] java.lang.NullPointerException: Attempt to invoke virtual method 'java.nio.ByteBuffer android.media.Image$Plane.getBuffer()' on a null object reference

### ISSUE THREAD

**Issue by dunzhixuan** [googlesamples/mlkit#444]
**Describe the bug**
at com.google.mlkit.vision.mediapipe.utils.ImageConvertNativeUtils.getRgbBuffer(com.google.mlkit:mediapipe-internal@@17.0.0-beta6:11)
        at com.google.mlkit.vision.pose.internal.zzd.zzc(com.google.mlkit:pose-detection-common@@18.0.0-beta1:2)
        at com.google.mlkit.vision.pose.internal.zzd.run(com.google.mlkit:pose-detection-common@@18.0.0-beta1:1)
        at com.google.mlkit.vision.common.internal.MobileVisionBase.zza(com.google.mlkit:vision-common@@17.0.0:2)
        at com.google.mlkit.vision.common.internal.zzd.call(Unknown Source:4)
        at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@18.0.0:8)
        at com.google.mlkit.common.sdkinternal.zzl.run(Unknown Source:10) 
        at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@18.0.0:2) 
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@18.0.0:4) 
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@18.0.0:1) 
        at com.google.mlkit.common.sdkinternal.zzi.run(Unknown Source:2) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@18.0.0:2) 
        at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2) 
        at java.lang.Thread.run(Thread.java:919) 

mlkitversion:
com.google.mlkit:pose-detection:18.0.0-beta1

**Comment by steven-chengji-yan** [comment]
Are you using CameraX API? Is it possible the Image you got from CameraX is closed earlier before MLKit finishes using it?

Did you get this issue from your own app or while using the ML Kit quickstart app? If from your own app, could you first help verify if the ML Kit quickstart app works fine on your device? If so, you could take a closer look to check the difference.

Feel free to share some code snippets here about the usage of CameraX and ML Kit API if it is not too complicated.

**Comment by steven-chengji-yan** [comment]
Close due to inactive.

Feel free to re-open if you are still working on it.
