### ISSUE TITLE
[Bug report] Caused by: java.lang.IllegalStateException: Image is already closed

### ISSUE THREAD

**Issue by dunzhixuan** [googlesamples/mlkit#445]
**Describe the bug**
at android.media.Image.throwISEIfImageIsInvalid(Image.java:72)
        at android.media.ImageReader$SurfaceImage.getPlanes(ImageReader.java:895)
        at com.google.mlkit.vision.common.zzb.zzb(com.google.mlkit:vision-common@@17.0.0:1)
        at com.google.mlkit.vision.common.InputImage.getPlanes(com.google.mlkit:vision-common@@17.0.0:1)
        at com.google.mlkit.vision.mediapipe.utils.ImageConvertNativeUtils.getRgbBuffer(com.google.mlkit:mediapipe-internal@@17.0.0-beta6:6)
        at com.google.mlkit.vision.pose.internal.zzd.zzc(com.google.mlkit:pose-detection-common@@18.0.0-beta1:2)
        at com.google.mlkit.vision.pose.internal.zzd.run(com.google.mlkit:pose-detection-common@@18.0.0-beta1:1)
        at com.google.mlkit.vision.common.internal.MobileVisionBase.zza(com.google.mlkit:vision-common@@17.0.0:2)
        at com.google.mlkit.vision.common.internal.zzd.call(Unknown Source:4)
        at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@18.0.0:8)
        at com.google.mlkit.common.sdkinternal.zzl.run(Unknown Source:10) 
        at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@18.0.0:2) 
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@18.0.0:4) 
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@18.0.0:1) 
        at com.google.mlkit.common.sdkinternal.zzi.run(Unknown Source:2) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@18.0.0:2) 
        at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by steven-chengji-yan** [comment]
This could be the same issue as https://github.com/googlesamples/mlkit/issues/444

**Comment by steven-chengji-yan** [comment]
Close due to inactive.

Feel free to re-open if you are still working on it.
