### ISSUE TITLE
[Bug report] Title for the bugML Kit Dynamic module feature crashed and showing resource not found on release build opened after forcefully closed app

### ISSUE THREAD

**Issue by spporan** [googlesamples/mlkit#514]
We are developing an app that has a feature translation. We want to implement a translation feature on-demand using ```com.google.mlkit:playstore-dynamic-feature-support:16.0.0-beta2``` with google MLkit ```com.google.mlkit:translate:17.0.0```

It is working perfectly on debug build. It has also worked on the release build after the on-demand dynamic feature installation was done until the app forcefully stopped. After the app stopped forcefully and open again that time on-demand feature doesn't work and threw an exception like ```resource not found exception```.

Here is the exception message:

    android.content.res.Resources$NotFoundException: Resource ID #0x7e030000
            at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:292)
            at android.content.res.Resources.loadXmlResourceParser(Resources.java:2390)
            at android.content.res.Resources.getXml(Resources.java:1392)
            at com.google.android.gms.internal.mlkit_translate.zzpi.zza(com.google.mlkit:translate@@17.0.0:4)
            at com.google.android.gms.internal.mlkit_translate.zzpp.zzi(com.google.mlkit:translate@@17.0.0:1)
            at com.google.mlkit.nl.translate.internal.zzad.<init>(com.google.mlkit:translate@@17.0.0:1)
            at com.google.mlkit.nl.translate.zzg.create(com.google.mlkit:translate@@17.0.0:2)
            at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:132)
            at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(Unknown Source:4)
            at com.google.firebase.components.Lazy.get(Lazy.java:53)
            at com.google.firebase.components.AbstractComponentContainer.get(AbstractComponentContainer.java:27)
            at com.google.firebase.components.ComponentRuntime.get(ComponentRuntime.java:45)
            at com.google.firebase.components.RestrictedComponentContainer.get(RestrictedComponentContainer.java:89)
            at com.google.mlkit.nl.translate.zzd.create(com.google.mlkit:translate@@17.0.0:2)
            at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:132)
            at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(Unknown Source:4)
            at com.google.firebase.components.Lazy.get(Lazy.java:53)
            at com.google.firebase.components.AbstractComponentContainer.get(AbstractComponentContainer.java:27)
            at com.google.firebase.components.ComponentRuntime.get(ComponentRuntime.java:45)
            at com.google.firebase.components.RestrictedComponentContainer.get(RestrictedComponentContainer.java:89)
            at com.google.mlkit.nl.translate.zze.create(com.google.mlkit:translate@@17.0.0:2)
            at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:132)
            at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(Unknown Source:4)
            at com.google.firebase.components.Lazy.get(Lazy.java:53)
            at com.google.firebase.components.AbstractComponentContainer.get(AbstractComponentContainer.java:27)
            at com.google.firebase.components.ComponentRuntime.get(ComponentRuntime.java:45)
            at com.google.mlkit.common.sdkinternal.MlKitContext.get(com.google.mlkit:common@@18.0.0:3)
            at com.google.mlkit.nl.translate.Translation.getClient(com.google.mlkit:translate@@17.0.0:1)

It will again work when I update another version from the play store.

Anyone can help, It will be appreciated.

**Comment by zhouyiself** [comment]
Saloni, thanks for the report!

Could you provide the library version you're using? Also do you have any test input that could reproduce the crash?
