### ISSUE TITLE
[Bug report] `NullPointerException` when reading QR code from specific image

### ISSUE THREAD

**Issue by AlexV525** [googlesamples/mlkit#569]
**Describe the bug**
When I was trying to read a specific image file that contains a valid QR code, the scanner throws an NPE or is unable to read the data.

```
D/VisionProcessorBase: Failed to process. Error: Internal error has occurred when executing ML Kit tasks
W/System.err: com.google.mlkit.common.MlKitException: Internal error has occurred when executing ML Kit tasks
W/System.err:     at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@18.5.0:9)
W/System.err:     at com.google.mlkit.common.sdkinternal.zzn.run(Unknown Source:10)
W/System.err:     at com.google.mlkit.common.sdkinternal.zzt.run(com.google.mlkit:common@@18.5.0:2)
W/System.err:     at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@18.5.0:4)
W/System.err:     at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@18.5.0:1)
W/System.err:     at com.google.mlkit.common.sdkinternal.zzk.run(Unknown Source:2)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@18.5.0:2)
W/System.err:     at com.google.mlkit.common.sdkinternal.zzi.run(Unknown Source:2)
W/System.err:     at java.lang.Thread.run(Thread.java:923)
W/System.err: Caused by: java.lang.NullPointerException: Attempt to get length of null array
W/System.err:     at com.google.android.gms.internal.mlkit_vision_barcode_bundled.zzec.zzJ(com.google.mlkit:barcode-scanning@@17.0.2:1)
W/System.err:     at com.google.photos.vision.barhopper.BarhopperProto$BarhopperResponse.zzb(com.google.mlkit:barcode-scanning@@17.0.2:1)
W/System.err:     at com.google.android.libraries.barhopper.BarhopperV3.toProto(com.google.mlkit:barcode-scanning@@17.0.2:1)
W/System.err:     at com.google.android.libraries.barhopper.BarhopperV3.recognize(com.google.mlkit:barcode-scanning@@17.0.2:11)
W/System.err:     at com.google.mlkit.vision.barcode.bundled.internal.zza.zzb(com.google.mlkit:barcode-scanning@@17.0.2:5)
W/System.err:     at com.google.android.gms.internal.mlkit_vision_barcode_bundled.zzbk.zza(com.google.mlkit:barcode-scanning@@17.0.2:3)
W/System.err:     at com.google.android.gms.internal.mlkit_vision_barcode_bundled.zzb.onTransact(com.google.mlkit:barcode-scanning@@17.0.2:3)
W/System.err:     at android.os.Binder.transact(Binder.java:1054)
W/System.err:     at com.google.android.gms.internal.mlkit_vision_barcode.zza.zzb(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.0.0:2)
W/System.err:     at com.google.android.gms.internal.mlkit_vision_barcode.zzox.zzd(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.0.0:4)
W/System.err:     at com.google.mlkit.vision.barcode.internal.zzl.zza(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.0.0:14)
W/System.err:     at com.google.mlkit.vision.barcode.internal.zzi.zzc(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.0.0:3)
W/System.err:     at com.google.mlkit.vision.barcode.internal.zzi.run(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.0.0:1)
W/System.err:     at com.google.mlkit.vision.common.internal.MobileVisionBase.zza(com.google.mlkit:vision-common@@17.2.1:2)
W/System.err:     at com.google.mlkit.vision.common.internal.zza.call(Unknown Source:4)
W/System.err:     at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@18.5.0:8)
W/System.err: 	... 10 more
E/BarcodeProcessor: Barcode detection failed com.google.mlkit.common.MlKitException: Internal error has occurred when executing ML Kit tasks
```

**To Reproduce**

The image contains some personal private info, if it's applicable, please leave an email address then I can send the original image.

Example Steps to reproduce the behavior in the sample app:
1. Run the "ML Kit Vision Quickstart" example.
2. Click on 'Run the ML kit quickstart written in Kotlin'
2. Click on 'StillImageActivity'
3. Change "Object Detection" to "Barcode Scanning"
4. Choose the image from the album.

**SDK Info:**
 - com.google.mlkit:barcode-scanning:17.0.2
 - GoogleMLKit/BarcodeScanning ~3.2.0

**Smartphone:**
 - Device/Simulator: All devices (including Android and iOS)

**Comment by zhouyiself** [comment]
Thanks for the report! Can you share your image with zhouyiself@gmail.com?

**Comment by AlexV525** [comment]
> Thanks for the report! Can you share your image with [zhouyiself@gmail.com](mailto:zhouyiself@gmail.com)?

@zhouyiself Sure. The image has been sent.

**Comment by zeroDivider** [comment]
This happened to me too, will it be considered a d fixed soon?

**Comment by SilverDestiny** [comment]
Contacted @AlexV525 by email. Please share the image with me to reproduce this issue. Thanks!

**Comment by AlexV525** [comment]
> @AlexV525 Hi, I didn't see your image in the email list.

Can you check again?
![image](https://user-images.githubusercontent.com/15884415/194506320-aad799ac-13cc-42fe-b0c1-d1cf3e311479.png)

**Comment by SilverDestiny** [comment]
The root cause is the input Bitmap config is not ARGB_8888, and our engine only supports config ARGB_8888 for Bitmap underneath: https://developer.android.com/reference/android/graphics/Bitmap.Config

It works well for streaming mode, i.e. LivePreviewActivity and CameraXLivePreviewActivity

We'll consider converting Bitmap config to ARGB_8888 if not internally to fix this issue in later releases. Thanks for reporting this bug!

**Comment by SilverDestiny** [comment]
BTW, the original input Bitmap config is RGBA_F16

**Comment by edi2212** [comment]
ikstrimProm

**Comment by AlexV525** [comment]
> We'll consider converting Bitmap config to ARGB_8888 if not internally to fix this issue in later releases. Thanks for reporting this bug!

`BitmapFactory.Options.outConfig` [(link)](https://developer.android.com/reference/android/graphics/BitmapFactory.Options#outConfig) only supported from API 26, so it'll be good if we can convert the `Bitmap` if it's not `ARGB_8888` in the ML Kit internally.

For a workaround:

```kotlin
// Decodes without memory allocation.
val options = BitmapFactory.Options().apply { inJustDecodeBounds = true }
BitmapFactory.decodeFile(path, options)
val mlImage: InputImage = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O && options.outConfig != Bitmap.Config.ARGB_8888) {
    // Convert the bitmap to ARGB_8888 if available.
    InputImage.fromBitmap(
        BitmapFactory.decodeFile(path).copy(Bitmap.Config.ARGB_8888, false),
        0
    )
} else {
    // Use the original bitmap.
    InputImage.fromFilePath(context, Uri.fromFile(File(path)))
}
```

**Comment by SilverDestiny** [comment]
https://developer.android.com/reference/android/graphics/Bitmap#getConfig() could be used to get the config from bitmap?

**Comment by AlexV525** [comment]
> https://developer.android.com/reference/android/graphics/Bitmap#getConfig() could be used to get the config from bitmap?

Yes, and it requires a memory allocation to read the actual data in IIRC.

**Comment by AlexV525** [comment]
Workaround with an actual allocation:

```kotlin
val mlImage: InputImage
val shouldConvertBitmap: Boolean
var decodedBitmap: Bitmap? = null
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
    // Decode the bitmap without memory allocation.
    val options = BitmapFactory.Options().apply { inJustDecodeBounds = true }
    BitmapFactory.decodeFile(path, options)
    shouldConvertBitmap = options.outConfig != Bitmap.Config.ARGB_8888
} else {
    val bitmap = BitmapFactory.decodeFile(path)
    shouldConvertBitmap = bitmap.config != Bitmap.Config.ARGB_8888
    // Cache the decoded bitmap.
    decodedBitmap = bitmap
}
mlImage = if (shouldConvertBitmap) {
    // Convert the bitmap to ARGB_8888 if available.
    val bitmap = decodedBitmap ?: BitmapFactory.decodeFile(path)
    InputImage.fromBitmap(bitmap.copy(Bitmap.Config.ARGB_8888, false), 0)
} else {
    // Use the original bitmap.
    InputImage.fromFilePath(this, Uri.fromFile(File(path)))
}
```

**Comment by AlexV525** [comment]
@miworking3 This also happened on iOS, so iOS should provide the same ability to convert if images are not `ARGB_8888`.

**Comment by AlexV525** [comment]
iOS workaround (I don't use unwrapping here, feel free to modify if it's worth in your code):

```swift
var image: UIImage? = UIImage.init(contentsOfFile: path)
if (image == nil) {
    // Throw something.
}
let fileExtension = URL(fileURLWithPath: path).pathExtension.lowercased()
// Convert all PNG to JPEG to avoid unsupported formats from ML Kit.
if (fileExtension == "png") {
    let imageData = image!.jpegData(compressionQuality: 1)
    image = UIImage(data: imageData!)
    if (image == nil) {
        // Throw something.
    }
}
let visionImage = VisionImage(image: image!)
visionImage.orientation = image!.imageOrientation
```
