### ISSUE TITLE
[Bug report] Failed to find provider com.google.android.gsf.gservices for user 0;expected to find a valid ContentProvider for this authority

### ISSUE THREAD

**Issue by cgbgh** [googlesamples/mlkit#575]
I am developing an app with google digital ink recognition 'com.google.mlkit:digital-ink-recognition:18.0.0', but it crashed when initial.

Here is the exception message:

java. Lang. SecurityException: Failed to find provider com.google.android.gsf.gservices for user 0; expected to find a valid ContentProvider for this authority
at android.os.Parcel.createException (Parcel. java: 1950)
at android.os.Parcel.readException (Parcel. java: 1918)
at android.os.Parcel.readException (Parcel.iava: 1868)
at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:779)
at android.content.ContentResolver.registerContentObserver(ContentResolver.iava:1972)
at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1961)
at com.google.android.gms.internal.mlkit _vision_ digital_ ink.zzom.<init>(com.google.mlkit:digital-ink-recognition@016.0.0:11)
at com.google.android.gms.internal.mlkit_vision_digital_ink.zzom.zza(com.qoogle.mlkit:digital-ink-recognition@016.0.0:5)
at com.google.android.gms.internal.mlkit_vision_digital_ink.zzow.zzc(com.qoogle.mlkit:digital-ink-recognition@@16.0.0:53)
at com.google.android.gms.internal.mlkit_vision_digital_ink.zzbaq.zzb(com.google.mlkit:digital-ink-recognition@@16.0.0:3)
at com.google.android.gms.internal.mlkit_vision_digital_ink.zzbao.zzc(com.qoogle.mlkit:digital-ink-recognition@@16.0.0:2)
at com.google.android.gms.internal.mlkit _vision_ digital_ ink.zzit.zzb(com.google.mlkit:digital-ink-recognition@@16.0.0:77)
at com.google.android.gms.internal.mlkit_vision_digital_ink.zzio.zzd(com.google.mlkit:digital-ink-recognition@@16.0.0:76)
at com.google.android.gms.internal.mlkit_vision_digital_ ink.zzix.zza(Unknown Source:4
at com.google.android.gms.internal.mlkit_vision_digital_ink.zzafk.zza(com.google.mlkit:digital-ink-recognition@@16.0.0:7)
at com.google.android.gms.internal.mlkit_vision_digital_ink.zzafl.run(com.google.mlkit:digital-ink-recognition@@16.0.0:36)
at com.google.android.qms.internal.mlkit vision _digital ink.zzahk$zza.run(com.qoogle.mlkit:digital-ink-recognition@@16.0.0:24)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.iava:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

**Comment by ai-plays** [comment]
Hi cgbgh,

In the stacktrace, it shows "com.google.mlkit:digital-ink-recognition@@16.0.0", but you said you are using "com.google.mlkit:digital-ink-recognition:18.0.0".  Could you confirm the version?   Did you get any warning about version conflict when building the app?

How do you structure your app? Are you using [feature modules](https://developer.android.com/guide/playcore/feature-delivery)? If so, is the digital-ink part of the main apk or feature apk?

**Comment by cgbgh** [comment]
您的邮件我已经收到了，祝您天天开心！-----cgb

**Comment by ai-plays** [comment]
Close due to inactivity.

**Comment by cgbgh** [comment]
您的邮件我已经收到了，祝您天天开心！-----cgb
