### ISSUE TITLE
[Bug report]  Failed to find provider com.google.android.gsf.gservices for user 0

### ISSUE THREAD

**Issue by JuiceShui** [googlesamples/mlkit#583]
I am developing an app with google digital ink recognition 'com.google.mlkit:digital-ink-recognition:17.0.0' as a module.
If I add android:sharedUserId="android.uid.system" to Manifest,it crashed.
But if I don't add android:sharedUserId="android.uid.system" ,it's ok.
There are some logs:
 java.lang.SecurityException: Failed to find provider com.google.android.gsf.gservices for user 0; expected to find a valid ContentProvider for this authority
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:1229)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:2627)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:2615)
        at com.google.android.gms.internal.mlkit_vision_digital_ink.zzve.<init>(com.google.mlkit:digital-ink-recognition@@17.0.0:2)
        at com.google.android.gms.internal.mlkit_vision_digital_ink.zzve.zza(com.google.mlkit:digital-ink-recognition@@17.0.0:2)
        at com.google.android.gms.internal.mlkit_vision_digital_ink.zzvq.zzb(com.google.mlkit:digital-ink-recognition@@17.0.0:6)
        at com.google.android.gms.internal.mlkit_vision_digital_ink.zzbsh.zzc(com.google.mlkit:digital-ink-recognition@@17.0.0:1)
        at com.google.android.gms.internal.mlkit_vision_digital_ink.zzbse.zzd(com.google.mlkit:digital-ink-recognition@@17.0.0:1)
        at com.google.android.gms.internal.mlkit_vision_digital_ink.zzfx.zzk(com.google.mlkit:digital-ink-recognition@@17.0.0:1)
        at com.google.android.gms.internal.mlkit_vision_digital_ink.zzof.zza(com.google.mlkit:digital-ink-recognition@@17.0.0:1)
        at com.google.android.gms.internal.mlkit_vision_digital_ink.zzado.zza(com.google.mlkit:digital-ink-recognition@@17.0.0:1)
        at com.google.android.gms.internal.mlkit_vision_digital_ink.zzog.zza(com.google.mlkit:digital-ink-recognition@@17.0.0:1)
        at com.google.android.gms.internal.mlkit_vision_digital_ink.zzmf.zza(com.google.mlkit:digital-ink-recognition@@17.0.0:1)
        at com.google.android.gms.internal.mlkit_vision_digital_ink.zznh.zzn(com.google.mlkit:digital-ink-recognition@@17.0.0:1)
        at com.google.android.gms.internal.mlkit_vision_digital_ink.zzmm.zza(Unknown Source:4)
        at com.google.android.gms.internal.mlkit_vision_digital_ink.zzamb.zzd(com.google.mlkit:digital-ink-recognition@@17.0.0:2)
        at com.google.android.gms.internal.mlkit_vision_digital_ink.zzamd.run(com.google.mlkit:digital-ink-recognition@@17.0.0:9)
        at com.google.android.gms.internal.mlkit_vision_digital_ink.zzaog.run(com.google.mlkit:digital-ink-recognition@@17.0.0:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

**Comment by JuiceShui** [comment]
Anybody can answer?
My device does not have Google services.
If I don't add android:sharedUserId="android.uid.system" to Manifest ,it can run well.
If I add android:sharedUserId="android.uid.system" to Manifest,there will show some error about "Failed to find provider com.google.android.gsf.gservices for user 0".
Why？

**Comment by ai-plays** [comment]
Hi JuiceShui,

On the Android dev doc, it says android:sharedUserId is deprecated due to "non-deterministic behavior within the package manager"https://developer.android.com/guide/topics/manifest/manifest-element .  Could you see if you can achieve what you want with other non-deprecated ways?

(BTW, the latest digital-ink SDK version is 18.0.0 if you want to be up-to-date).
