### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed "----lib/arm64/libface_detector_v2_jni.so" has bad ELF magic: 00000000

### ISSUE THREAD

**Issue by vajjasivateja** [googlesamples/mlkit#632]
**Describe the bug**
In my firebase crashlytics recently I am seeing repeated bug which is below,

Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~ic2W0xno23mcxTN9NrOZqw==/com.xxxxxxx.xxxxx.app-lGoYxe43v8GESjnUcqYZeQ==/lib/arm64/libface_detector_v2_jni.so" has bad ELF magic: 00000000
       at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
       at java.lang.System.loadLibrary(System.java:1664)
       at com.google.mlkit.vision.face.bundled.internal.ThickFaceDetectorCreator.<clinit>(com.google.mlkit:face-detection@@16.1.5:1)
       at java.lang.Class.newInstance(Class.java)
       at com.google.android.gms.dynamite.DynamiteModule.instantiate(com.google.android.gms:play-services-basement@@18.0.0:2)
       at com.google.mlkit.vision.face.internal.zza.zze(com.google.android.gms:play-services-mlkit-face-detection@@17.0.1:2)
       at com.google.mlkit.vision.face.internal.zza.zzg(com.google.android.gms:play-services-mlkit-face-detection@@17.0.1:1)
       at com.google.mlkit.vision.face.internal.zza.zzf(com.google.android.gms:play-services-mlkit-face-detection@@17.0.1:22)
       at com.google.mlkit.vision.face.internal.zza.zzd(com.google.android.gms:play-services-mlkit-face-detection@@17.0.1:2)
       at com.google.mlkit.vision.face.internal.zzh.load(com.google.android.gms:play-services-mlkit-face-detection@@17.0.1:1)
       at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@18.1.0:4)
       at com.google.mlkit.common.sdkinternal.zzl.run(com.google.mlkit:common@@18.1.0:10)
       at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@18.1.0:2)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@18.1.0:4)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@18.1.0:1)
       at com.google.mlkit.common.sdkinternal.zzi.run(com.google.mlkit:common@@18.1.0:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@18.1.0:2)
       at com.google.mlkit.common.sdkinternal.zzj.run(com.google.mlkit:common@@18.1.0:2)
       at java.lang.Thread.run(Thread.java:923)

**Comment by jackqdyulei** [comment]
Thanks for your report. For those repeated bugreports, are they all coming from OPPO and Android 11? If not, please help to list out the affected devices & API level.

**Comment by pavel163** [comment]
Hi. I have faced with the same problem.

<img width="1148" alt="Снимок экрана 2023-05-02 в 14 43 39" src="https://user-images.githubusercontent.com/9054609/235645877-1b61b467-05c8-43d3-b6b3-1bac49231f2c.png">

<img width="415" alt="Снимок экрана 2023-05-02 в 14 44 04" src="https://user-images.githubusercontent.com/9054609/235645947-e9d98a56-a265-462c-8c73-58bde2b8d539.png">

**Comment by pavel163** [comment]
Hi, @jackqdyulei 
Do you have any updates?

**Comment by pavel163** [comment]
Hi, @vajjasivateja 
Have you found how to fix it?

**Comment by jackqdyulei** [comment]
Hi Pavel, sorry for the late reply. Could you help to provide the failing device list(e.g. Oppo xxx) with OS version. I will try to repro from my side. Thanks!

**Comment by pavel163** [comment]
Hi @jackqdyulei. Below is the list of devices

Vivo: Y16(android 12), Y02s (android 12), Y02t (android 13)
Oppo: A17k (android 12), A57 (android 12)
Samsung:  Galaxy A14 (android 13)
Huawei: PPA-LX2 (android 10), MED-LX9 (android 10)
Transsion - Uniso: Tecno POP 5 LTE (android 11)

**Comment by haytham-c01** [comment]
I am getting the same crash reported by Firebase Crashlytics.

# General
Occurrence: the crash occurred 55 times for 33 users within 90 days.

Dependency: `com.google.mlkit:face-detection:16.1.5`

## Android OS
- 40% - Android 12
- 34% - Android 11
- 22% - Android 13
- 4% - Android 10

## Devices
- 27% - Xiaomi
  - 7% - Redmi Note 12 Pro 5G
  - 5% - POCO M3
  - 4% - REDMI NOTE 9 Pro
  - 3% - Redmi Note 11 Pro 5G
  - 2% - Redmi Note 11 Pro Max
  - 2% - Poco X3 NFC
  - 2% - Redmi 9A
  - 2% - Redmi 10 2022
- 20% - Samsung
  - 4% - Galaxy S23
  - 4% - Galaxy Z Fold2 5G
  - 3% - Galaxy A80
  - 3% - Galaxy A13
  - 2% - Galaxy S23 Ultra
  - 2% - Galaxy S23 Ultra 5G
  - 2% - Galaxy A04
- 13% - Honor
  - 4% - Honor X6
  - 4% - Honor X9a 5G
  - 3% - Honor 50 Lite
  - 2% - Honor X8 a
- 7% - Transsion - Unisoc
  - 4% Canon 20 Pro
  - 3% Tecno POP 7
- 33% - Other (8)
  - 7% - OPPO
  - 7% - Transsion - Mediatek
  - 4% - Motorola
  - 4% - Transsion
  - 4% - Transsion

## Exceptions
```
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/app/~~6-LXVzl5kHBKBV1QjfYGSA==/com.placeholder.package-3VfFUnRvMZ3TfRsXcJ2wvg==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libface_detector_v2_jni.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
       at java.lang.Runtime.loadLibrary0(Runtime.java:998)
       at java.lang.System.loadLibrary(System.java:1661)
       at com.google.mlkit.vision.face.bundled.internal.ThickFaceDetectorCreator.<clinit>(com.google.mlkit:face-detection@@16.1.5:1)
       at java.lang.Class.newInstance(Class.java)
       at com.google.android.gms.dynamite.DynamiteModule.instantiate(com.google.android.gms:play-services-basement@@18.1.0:2)
       at com.google.mlkit.vision.face.internal.zza.zze(com.google.android.gms:play-services-mlkit-face-detection@@17.0.1:2)
       at com.google.mlkit.vision.face.internal.zza.zzg(com.google.android.gms:play-services-mlkit-face-detection@@17.0.1:1)
       at com.google.mlkit.vision.face.internal.zza.zzf(com.google.android.gms:play-services-mlkit-face-detection@@17.0.1:5)
       at com.google.mlkit.vision.face.internal.zza.zzd(com.google.android.gms:play-services-mlkit-face-detection@@17.0.1:2)
       at com.google.mlkit.vision.face.internal.zzh.load(com.google.android.gms:play-services-mlkit-face-detection@@17.0.1:1)
       at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@18.1.0:4)
       at com.google.mlkit.common.sdkinternal.zzl.run(com.google.mlkit:common@@18.1.0:10)
       at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@18.1.0:2)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@18.1.0:4)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@18.1.0:1)
       at com.google.mlkit.common.sdkinternal.zzi.run(com.google.mlkit:common@@18.1.0:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@18.1.0:2)
       at com.google.mlkit.common.sdkinternal.zzj.run(com.google.mlkit:common@@18.1.0:2)
       at java.lang.Thread.run(Thread.java:1012)
```

```
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/app/com.placeholder.package-Mg7-zjnjOvvvwrGahPDYeQ==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libface_detector_v2_jni.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
       at java.lang.System.loadLibrary(System.java:1667)
       at com.google.mlkit.vision.face.bundled.internal.ThickFaceDetectorCreator.<clinit>(com.google.mlkit:face-detection@@16.1.5:1)
       at java.lang.Class.newInstance(Class.java)
       at com.google.android.gms.dynamite.DynamiteModule.instantiate(com.google.android.gms:play-services-basement@@18.1.0:2)
       at com.google.mlkit.vision.face.internal.zza.zze(com.google.android.gms:play-services-mlkit-face-detection@@17.0.1:2)
       at com.google.mlkit.vision.face.internal.zza.zzg(com.google.android.gms:play-services-mlkit-face-detection@@17.0.1:1)
       at com.google.mlkit.vision.face.internal.zza.zzf(com.google.android.gms:play-services-mlkit-face-detection@@17.0.1:5)
       at com.google.mlkit.vision.face.internal.zza.zzd(com.google.android.gms:play-services-mlkit-face-detection@@17.0.1:2)
       at com.google.mlkit.vision.face.internal.zzh.load(com.google.android.gms:play-services-mlkit-face-detection@@17.0.1:1)
       at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@18.1.0:4)
       at com.google.mlkit.common.sdkinternal.zzl.run(com.google.mlkit:common@@18.1.0:10)
       at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@18.1.0:2)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@18.1.0:4)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@18.1.0:1)
       at com.google.mlkit.common.sdkinternal.zzi.run(com.google.mlkit:common@@18.1.0:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@18.1.0:2)
       at com.google.mlkit.common.sdkinternal.zzj.run(com.google.mlkit:common@@18.1.0:2)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by jackqdyulei** [comment]
Hi [haytham-c01](https://github.com/haytham-c01), to understand the issue better, could you help to

1) Check your apk to make sure the native library is truly bundled. I believe so however want to sanity check
2) Check whether this is a constant failing on specific device(e.g. Galaxy S23)

Thanks!

**Comment by haytham-c01** [comment]
@jackqdyulei Sorry for the delay, I overlooked the email for your reply.

1. I checked both the APK generated by the Android Studio build and the one installed on the device from the "device explorer" and both include the ".so" library.
2. Unfortunately, I don't have access to an exact model right now.

**Comment by b-basoglu** [comment]
I  am following this issue nearly for 4 months now. Is there any update? I am facing the same issue.

Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libface_detector_v2_jni.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
       at java.lang.Runtime.loadLibrary0(Runtime.java:998)
       at java.lang.System.loadLibrary(System.java:1661)
       at com.google.mlkit.vision.face.bundled.internal.ThickFaceDetectorCreator.<clinit>(com.google.mlkit:face-detection@@16.1.5:1)
       at java.lang.Class.newInstance(Class.java)
       at com.google.android.gms.dynamite.DynamiteModule.instantiate(com.google.android.gms:play-services-basement@@18.1.0:2)
       at com.google.mlkit.vision.face.internal.zza.zze(com.google.android.gms:play-services-mlkit-face-detection@@17.0.1:2)
       at com.google.mlkit.vision.face.internal.zza.zzg(com.google.android.gms:play-services-mlkit-face-detection@@17.0.1:1)
       at com.google.mlkit.vision.face.internal.zza.zzf(com.google.android.gms:play-services-mlkit-face-detection@@17.0.1:22)
       at com.google.mlkit.vision.face.internal.zza.zzd(com.google.android.gms:play-services-mlkit-face-detection@@17.0.1:2)
       at com.google.mlkit.vision.face.internal.zzh.load(zzh.java:1)
       at com.google.mlkit.common.sdkinternal.ModelResource.zza(ModelResource.java:4)
       at com.google.mlkit.common.sdkinternal.zzl.run(com.google.mlkit:common@@18.1.0:38)
       at com.google.mlkit.common.sdkinternal.zzp.run(zzp.java:2)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(MlKitThreadPool.java:4)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(MlKitThreadPool.java:1)
       at com.google.mlkit.common.sdkinternal.zzi.run(zzi.java:89)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(MlKitThreadPool.java:2)
       at com.google.mlkit.common.sdkinternal.zzj.run(com.google.mlkit:common@@18.1.0:13)
       at java.lang.Thread.run(Thread.java:1012)

<img width="612" alt="Screenshot 2023-09-07 at 21 34 24" src="https://github.com/googlesamples/mlkit/assets/36642074/865162d2-f206-4fe3-acbf-d83259452964">
<img width="612" alt="Screenshot 2023-09-07 at 21 34 17" src="https://github.com/googlesamples/mlkit/assets/36642074/7f5b096d-997c-461f-be94-6dd5fe669f36">

* 64%Xiaomi
-19%Redmi Note 9 Pro
-18%Redmi Note 11S
-9%Redmi Note 10
-18%Other (2)

* %27 Samsung
-9%Galaxy A51
-9%Galaxy A13
-9%Galaxy A12

* Honor 50

gradle-8.0 (8.0.2) - Compile sdk & Target sdk 33

I am generating bundle not apk.
        
        ndk {
            abiFilters "arm64-v8a", "armeabi-v7a"
        }

implementation "com.google.mlkit:face-detection:16.1.5"

**Comment by AradiPatrik** [comment]
I am facing the same issue. Couldn't reproduce it with the devices available to me but I see the error in crashlytics and received a one star review because the face detection not working...

<img width="725" alt="image" src="https://github.com/googlesamples/mlkit/assets/16306605/801dad72-405e-4bea-b733-d3a4788f8f37">

The .so is there in my aab.

Affected devices (so far):
Pixel 6 Pro - Android 12
Nexus 5X - Android 8.1.0

Here is the stack trace:
```
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libface_detector_v2_jni.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
       at java.lang.Runtime.loadLibrary0(Runtime.java:998)
       at java.lang.System.loadLibrary(System.java:1656)
       at com.google.mlkit.vision.face.bundled.internal.ThickFaceDetectorCreator.<clinit>(com.google.mlkit:face-detection@@16.1.5:1)
       at java.lang.Class.newInstance(Class.java)
       at com.google.android.gms.dynamite.DynamiteModule.instantiate(com.google.android.gms:play-services-basement@@18.1.0:2)
       at com.google.mlkit.vision.face.internal.zza.zze(zza.java:2)
       at com.google.mlkit.vision.face.internal.zza.zzg(zza.java:1)
       at com.google.mlkit.vision.face.internal.zza.zzf(zza.java:5)
       at com.google.mlkit.vision.face.internal.zza.zzd(zza.java:2)
       at com.google.mlkit.vision.face.internal.zzh.load(com.google.android.gms:play-services-mlkit-face-detection@@17.0.1:1)
       at com.google.mlkit.common.sdkinternal.ModelResource.zza(ModelResource.java:4)
       at com.google.mlkit.common.sdkinternal.zzl.run(zzl.java:47)
       at com.google.mlkit.common.sdkinternal.zzp.run(zzp.java:2)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(MlKitThreadPool.java:4)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(MlKitThreadPool.java:1)
       at com.google.mlkit.common.sdkinternal.zzi.run(zzi.java:42)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(MlKitThreadPool.java:2)
       at com.google.mlkit.common.sdkinternal.zzj.run(zzj.java:17)
       at java.lang.Thread.run(Thread.java:920)
```

The weird thing is that I didn't touch the face detection code since half a year and this started happening for my latest release.

Any pointers on how to fix this issue?

**Comment by adonese** [comment]
Having the same error as well. On oneplus device.

**Comment by slice-tanyaa** [comment]
Any idea on how to fix this? Is it related to NDK. 
https://stackoverflow.com/questions/62612144/my-app-crashes-when-opening-on-an-android-device-app-keeps-stopping-error

**Comment by b-basoglu** [comment]
I was facing similar issues, you can details above.

**Why are we facing this issue?** -> The bundle that is distributed the user is missing libface_detector_v2_jni.so. That is correct it is missing but not because of you. It is completely Google's fault, not yours.

**Why we can not reproduce ourself?** -> Because you did not do anything wrong. You uploaded and tested on a correct bundle. 

**What is the solution then?** ->
build.gradle
`implementation "com.google.android.play:core:1.10.3"`

```
class App : Application() {
...
    override fun onCreate() {
        if (MissingSplitsManagerFactory.create(this).disableAppIfMissingRequiredSplits()) {
            // Skip app initialization.
            return
        }
        ...
   }
   ...
}
```
I know MissingSplitsManagerFactory is deprecated but after checking this way issues are gone now.
<img width="1368" alt="Screenshot 2024-02-16 at 06 52 23" src="https://github.com/googlesamples/mlkit/assets/36642074/3e681174-1c1f-428a-8f7f-37e75672cc71">

_Side note:_
We already know how to add this mlkit library like below.
build.gradle ->
```
android {
...
    defaultConfig {
...
        ndk {
            abiFilters "arm64-v8a", "armeabi-v7a"
        }
    }
...
}
dependencies {
  ...    
  implementation "com.google.mlkit:face-detection:16.1.5" (latest)
}
```

Please let me know if it also solve your problems.

**Comment by slice-tanyaa** [comment]
Below was missing in my code.

defaultConfig {
        ndk {
            abiFilters "arm64-v8a", "armeabi-v7a"
        }
    }

also
android.useDeprecatedNdk=true was not set.

could this be the reason?

**Comment by b-basoglu** [comment]
> Below was missing in my code.
> 
> defaultConfig { ndk { abiFilters "arm64-v8a", "armeabi-v7a" } }
> 
> also android.useDeprecatedNdk=true was not set.
> 
> could this be the reason?

-As I mentioned earlier if your app bundle has this ".so", and if it is working fine when you are testing and you are getting similar error of missing this file from the user which install app from google play, **it is not your fault. It is a google play error.** 

1- The abi filter below is not neccessary or must. It is optional you do not need to add. But "armeabi-v7a" and "x86" are older architectures and may be less common on newer devices, whether or not you need to support them depends on your target audience and the specific requirements of your application. It is optional.
**So you do not need to add the code below**
defaultConfig {
  ndk {
  abiFilters "arm64-v8a", "armeabi-v7a"
  }
}

2- I am not using "useDeprecatedNdk" which refers to using deprecated elements within the Native Development Kit (NDK) for Android development.

**Comment by dqh147258** [comment]
```
android {
    bundle {
        abi {
            enableSplit = false
        }
    }
}
```

Can we use this config to disable the google play package split so that the libface_detector_v2_jni.so can be kept

**Comment by b-basoglu** [comment]
> ```
> android {
>     bundle {
>         abi {
>             enableSplit = false
>         }
>     }
> }
> ```
> 
> Can we use this config to disable the google play package split so that the libface_detector_v2_jni.so can be kept

1-If you do this only one APK will be generated containing all native libraries for all supported ABIs. This will result in a larger APK size compared to having separate APKs for different ABIs. I do not suggest this.

2- I did not test that out and it is not an option for most of the applications.

3- Our filtered bundles already has libface_detector_v2_jni. I do not know how the process works on the google side but it does not deliver packages correctly sometimes.

**Comment by b-basoglu** [comment]
-keep class com.google.mlkit.** { *; }
-keep class com.google.android.gms.** { *; }
Add this two line to proguard-rules. Than it will be fixed.

Ignore my previous comments on this issue since MissingSplitsManagerFactory deprecated and its usage is completely removed. You will have following warning on your google play console if you are using MissingSplitsManagerFactory.

com.google.android.play:core has added this note for core:1.10.3:
Update your Play Core Maven dependency to an Android 14 compatible version! Your current Play Core library is incompatible with targetSdkVersion 34 (Android 14), which introduces a backwards-incompatible change to broadcast receivers to improve user security. As a reminder, from August 31, Google Play requires all new app releases to target Android 14. Update to the latest Play Core library version dependency to avoid app crashes.
