### ISSUE TITLE
[Android Translate Showcase] - Crash first time after giving the camera permission

### ISSUE THREAD

**Issue by esraa-ibrahim** [googlesamples/mlkit#68]
The app crashes the first time after giving the camera permission.

OS: Android 8.0.0
Device: HTC Desire 12+

Logcat:
```
2020-07-12 00:09:11.903 8419-8419/com.google.mlkit.showcase.translate E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.mlkit.showcase.translate, PID: 8419
    java.lang.IllegalStateException: Camera initialization failed.
        at com.google.mlkit.showcase.translate.main.MainFragment.bindCameraUseCases(MainFragment.kt:214)
        at com.google.mlkit.showcase.translate.main.MainFragment.access$bindCameraUseCases(MainFragment.kt:54)
        at com.google.mlkit.showcase.translate.main.MainFragment$onRequestPermissionsResult$1.run(MainFragment.kt:347)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6565)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

After some investigations, it seems that when accepting the camera permission we should initialize the camera by calling setUpCamera instead of calling bindCameraUseCases
```
if (allPermissionsGranted()) {
                viewFinder.post { bindCameraUseCases() }
            }
```

![Translate_Permission_Crash](https://user-images.githubusercontent.com/3535585/87234564-8929fc00-c3d2-11ea-999f-7b96b047981c.gif)

**Comment by sheepmaster** [comment]
Thanks for the investigation!
