### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by empquin** [googlesamples/mlkit#729]
Facing UnsatisfiedLinkError on multiple OS.
SDK version 17.1.0

Here is crash report on arm64_v8a device.

```
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/app/~~_ctgKe20PjzlN8JgAatQCg==/blibli.mobile.commerce-mlw3t94TVRZME4sZH4vhIQ==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libbarhopper_v3.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
       at java.lang.Runtime.loadLibrary0(Runtime.java:998)
       at java.lang.System.loadLibrary(System.java:1661)
       at com.google.android.libraries.barhopper.BarhopperV3.<init>(com.google.mlkit:barcode-scanning@@17.1.0:1)
       at com.google.mlkit.vision.barcode.bundled.internal.zzb.zzc(com.google.mlkit:barcode-scanning@@17.1.0:1)
       at com.google.android.gms.internal.mlkit_vision_barcode_bundled.zzbk.zza(com.google.mlkit:barcode-scanning@@17.1.0:9)
       at com.google.android.gms.internal.mlkit_vision_barcode_bundled.zzb.onTransact(com.google.mlkit:barcode-scanning@@17.1.0:3)
       at android.os.Binder.transact(Binder.java:1179)
       at com.google.android.gms.internal.mlkit_vision_barcode.zza.zzc(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.2.0:2)
       at com.google.android.gms.internal.mlkit_vision_barcode.zzsw.zze(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.2.0:2)
       at com.google.mlkit.vision.barcode.internal.zzl.zza(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.2.0:3)
       at com.google.mlkit.vision.barcode.internal.zzi.zze(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.2.0:3)
       at com.google.mlkit.vision.barcode.internal.zzi.run(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.2.0:1)
       at com.google.mlkit.vision.common.internal.MobileVisionBase.zza(com.google.mlkit:vision-common@@17.3.0:2)
       at com.google.mlkit.vision.common.internal.zza.call(com.google.mlkit:vision-common@@17.3.0:4)
       at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@18.7.0:8)
       at com.google.mlkit.common.sdkinternal.zzn.run(com.google.mlkit:common@@18.7.0:10)
       at com.google.mlkit.common.sdkinternal.zzt.run(com.google.mlkit:common@@18.7.0:2)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@18.7.0:4)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@18.7.0:1)
       at com.google.mlkit.common.sdkinternal.zzk.run(com.google.mlkit:common@@18.7.0:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@18.7.0:2)
       at com.google.mlkit.common.sdkinternal.zzi.run(com.google.mlkit:common@@18.7.0:2)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by john990** [comment]
This Issue still exists in com.google.mlkit: text-recography: 16.0.1 . Does anyone solve it?

```
Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xxx--NIFZxyGkXFfPUXg8US9zQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx--NIFZxyGkXFfPUXg8US9zQ==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libmlkit_google_ocr_pipeline.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
       at java.lang.System.loadLibrary(System.java:1667)
       at com.google.mlkit.vision.text.bundled.common.zba.zbc(com.google.mlkit:text-recognition-bundled-common@@17.0.0:1)
       at com.google.android.gms.internal.mlkit_vision_text_bundled_common.zbnz.zba(com.google.mlkit:text-recognition-bundled-common@@17.0.0:16)
       at com.google.android.gms.internal.mlkit_vision_text_bundled_common.zbb.onTransact(com.google.mlkit:text-recognition-bundled-common@@17.0.0:3)
       at android.os.Binder.transact(Binder.java:914)
       at com.google.android.gms.internal.mlkit_vision_text_common.zza.zzc(com.google.android.gms:play-services-mlkit-text-recognition-common@@19.1.0:2)
       at com.google.android.gms.internal.mlkit_vision_text_common.zzuv.zze(com.google.android.gms:play-services-mlkit-text-recognition-common@@19.1.0:2)
       at com.google.mlkit.vision.text.internal.zzd.zza(com.google.android.gms:play-services-mlkit-text-recognition-common@@19.1.0:3)
       at com.google.mlkit.vision.text.internal.TextRecognizerTaskWithResource.zze(com.google.android.gms:play-services-mlkit-text-recognition-common@@19.1.0:2)
       at com.google.mlkit.vision.text.internal.TextRecognizerTaskWithResource.run(com.google.android.gms:play-services-mlkit-text-recognition-common@@19.1.0:1)
       at com.google.mlkit.vision.common.internal.MobileVisionBase.zza(MobileVisionBase.java:2)
       at com.google.mlkit.vision.common.internal.zza.call(zza.java:46)
       at com.google.mlkit.common.sdkinternal.ModelResource.zza(ModelResource.java:8)
       at com.google.mlkit.common.sdkinternal.zzn.run(zzn.java:105)
       at com.google.mlkit.common.sdkinternal.zzt.run(zzt.java:2)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(MlKitThreadPool.java:4)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(MlKitThreadPool.java:1)
       at com.google.mlkit.common.sdkinternal.zzi.run(com.google.mlkit:common@@18.11.0:44)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(MlKitThreadPool.java:2)
       at com.google.mlkit.common.sdkinternal.zzk.run(zzk.java:17)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by RandallXia** [comment]
Try adding this to your app‘s build.gradle
`
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
        }
`
it works for me

> This Issue still exists in com.google.mlkit: text-recography: 16.0.1 . Does anyone solve it?
> 
> ```
> Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xxx--NIFZxyGkXFfPUXg8US9zQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx--NIFZxyGkXFfPUXg8US9zQ==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libmlkit_google_ocr_pipeline.so"
>        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
>        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
>        at java.lang.System.loadLibrary(System.java:1667)
>        at com.google.mlkit.vision.text.bundled.common.zba.zbc(com.google.mlkit:text-recognition-bundled-common@@17.0.0:1)
>        at com.google.android.gms.internal.mlkit_vision_text_bundled_common.zbnz.zba(com.google.mlkit:text-recognition-bundled-common@@17.0.0:16)
>        at com.google.android.gms.internal.mlkit_vision_text_bundled_common.zbb.onTransact(com.google.mlkit:text-recognition-bundled-common@@17.0.0:3)
>        at android.os.Binder.transact(Binder.java:914)
>        at com.google.android.gms.internal.mlkit_vision_text_common.zza.zzc(com.google.android.gms:play-services-mlkit-text-recognition-common@@19.1.0:2)
>        at com.google.android.gms.internal.mlkit_vision_text_common.zzuv.zze(com.google.android.gms:play-services-mlkit-text-recognition-common@@19.1.0:2)
>        at com.google.mlkit.vision.text.internal.zzd.zza(com.google.android.gms:play-services-mlkit-text-recognition-common@@19.1.0:3)
>        at com.google.mlkit.vision.text.internal.TextRecognizerTaskWithResource.zze(com.google.android.gms:play-services-mlkit-text-recognition-common@@19.1.0:2)
>        at com.google.mlkit.vision.text.internal.TextRecognizerTaskWithResource.run(com.google.android.gms:play-services-mlkit-text-recognition-common@@19.1.0:1)
>        at com.google.mlkit.vision.common.internal.MobileVisionBase.zza(MobileVisionBase.java:2)
>        at com.google.mlkit.vision.common.internal.zza.call(zza.java:46)
>        at com.google.mlkit.common.sdkinternal.ModelResource.zza(ModelResource.java:8)
>        at com.google.mlkit.common.sdkinternal.zzn.run(zzn.java:105)
>        at com.google.mlkit.common.sdkinternal.zzt.run(zzt.java:2)
>        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(MlKitThreadPool.java:4)
>        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(MlKitThreadPool.java:1)
>        at com.google.mlkit.common.sdkinternal.zzi.run(com.google.mlkit:common@@18.11.0:44)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(MlKitThreadPool.java:2)
>        at com.google.mlkit.common.sdkinternal.zzk.run(zzk.java:17)
>        at java.lang.Thread.run(Thread.java:919)
> ```

**Comment by john990** [comment]
Thanks, but it doesn’t work for me; I’ve already set it up this way.

> Try adding this to your app‘s build.gradle `ndk { abiFilters "armeabi-v7a", "arm64-v8a" }` it works for me
> 
> > This Issue still exists in com.google.mlkit: text-recography: 16.0.1 . Does anyone solve it?
> > ```
> > Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xxx--NIFZxyGkXFfPUXg8US9zQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx--NIFZxyGkXFfPUXg8US9zQ==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libmlkit_google_ocr_pipeline.so"
> >        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
> >        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
> >        at java.lang.System.loadLibrary(System.java:1667)
> >        at com.google.mlkit.vision.text.bundled.common.zba.zbc(com.google.mlkit:text-recognition-bundled-common@@17.0.0:1)
> >        at com.google.android.gms.internal.mlkit_vision_text_bundled_common.zbnz.zba(com.google.mlkit:text-recognition-bundled-common@@17.0.0:16)
> >        at com.google.android.gms.internal.mlkit_vision_text_bundled_common.zbb.onTransact(com.google.mlkit:text-recognition-bundled-common@@17.0.0:3)
> >        at android.os.Binder.transact(Binder.java:914)
> >        at com.google.android.gms.internal.mlkit_vision_text_common.zza.zzc(com.google.android.gms:play-services-mlkit-text-recognition-common@@19.1.0:2)
> >        at com.google.android.gms.internal.mlkit_vision_text_common.zzuv.zze(com.google.android.gms:play-services-mlkit-text-recognition-common@@19.1.0:2)
> >        at com.google.mlkit.vision.text.internal.zzd.zza(com.google.android.gms:play-services-mlkit-text-recognition-common@@19.1.0:3)
> >        at com.google.mlkit.vision.text.internal.TextRecognizerTaskWithResource.zze(com.google.android.gms:play-services-mlkit-text-recognition-common@@19.1.0:2)
> >        at com.google.mlkit.vision.text.internal.TextRecognizerTaskWithResource.run(com.google.android.gms:play-services-mlkit-text-recognition-common@@19.1.0:1)
> >        at com.google.mlkit.vision.common.internal.MobileVisionBase.zza(MobileVisionBase.java:2)
> >        at com.google.mlkit.vision.common.internal.zza.call(zza.java:46)
> >        at com.google.mlkit.common.sdkinternal.ModelResource.zza(ModelResource.java:8)
> >        at com.google.mlkit.common.sdkinternal.zzn.run(zzn.java:105)
> >        at com.google.mlkit.common.sdkinternal.zzt.run(zzt.java:2)
> >        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(MlKitThreadPool.java:4)
> >        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(MlKitThreadPool.java:1)
> >        at com.google.mlkit.common.sdkinternal.zzi.run(com.google.mlkit:common@@18.11.0:44)
> >        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> >        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> >        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(MlKitThreadPool.java:2)
> >        at com.google.mlkit.common.sdkinternal.zzk.run(zzk.java:17)
> >        at java.lang.Thread.run(Thread.java:919)
> > ```
