### ISSUE TITLE
[Bug report] MLKIT Face Detection Model failed to download on Android 14

### ISSUE THREAD

**Issue by datbu178** [googlesamples/mlkit#760]
implementation 'com.google.android.gms:play-services-mlkit-face-detection:17.1.0'

//devices:
Samsung S23+
Android 14

//Error:
Error preloading model resource
com.google.mlkit.common.MlKitException: Waiting for the face module to be downloaded. Please wait.
	at com.google.mlkit.vision.face.internal.zza.zzd(com.google.android.gms:play-services-mlkit-face-detection@@17.1.0:10)
	at com.google.mlkit.vision.face.internal.zzh.load(com.google.android.gms:play-services-mlkit-face-detection@@17.1.0:1)
	at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@18.5.0:4)
	at com.google.mlkit.common.sdkinternal.zzn.run(Unknown Source:10)
	at com.google.mlkit.common.sdkinternal.zzt.run(com.google.mlkit:common@@18.5.0:2)
	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@18.5.0:4)
	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@18.5.0:1)
	at com.google.mlkit.common.sdkinternal.zzk.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@18.5.0:2)
	at com.google.mlkit.common.sdkinternal.zzi.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.vision.face found. Local version is 0 and remote version is 0.
	at com.google.android.gms.dynamite.DynamiteModule.load(com.google.android.gms:play-services-basement@@18.2.0:69)
	at com.google.mlkit.vision.face.internal.zza.zze(com.google.android.gms:play-services-mlkit-face-detection@@17.1.0:1)
	at com.google.mlkit.vision.face.internal.zza.zzg(com.google.android.gms:play-services-mlkit-face-detection@@17.1.0:2)
	at com.google.mlkit.vision.face.internal.zza.zzf(com.google.android.gms:play-services-mlkit-face-detection@@17.1.0:22)
	at com.google.mlkit.vision.face.internal.zza.zzd(com.google.android.gms:play-services-mlkit-face-detection@@17.1.0:5)
	at com.google.mlkit.vision.face.internal.zzh.load(com.google.android.gms:play-services-mlkit-face-detection@@17.1.0:1) 
	at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@18.5.0:4) 
	at com.google.mlkit.common.sdkinternal.zzn.run(Unknown Source:10) 
	at com.google.mlkit.common.sdkinternal.zzt.run(com.google.mlkit:common@@18.5.0:2) 
	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@18.5.0:4) 
	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@18.5.0:1) 
	at com.google.mlkit.common.sdkinternal.zzk.run(Unknown Source:2) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@18.5.0:2) 
	at com.google.mlkit.common.sdkinternal.zzi.run(Unknown Source:2) 
	at java.lang.Thread.run(Thread.java:1012) 

//=========================
Work fine on Android 12, 13. This error only appears on Android 14.

**Comment by jackqdyulei** [comment]
Hi [datbu178](https://github.com/datbu178), do you still having this issue?

When you test the module downloading on various API/devices, have you tried to remove cache on Google Play Services first(to remove the existing module)

**Comment by jackqdyulei** [comment]
Thanks,

1. Have you tried on real device, without Remote Test Lab
2. Could you provide full bug report, or more adb log. The log you posted just means the module has not been downloaded, which is not quite useful in this case

**Comment by jackqdyulei** [comment]
If the device doesn't have GMSCore module installed, it is WAI to have MlKitException for the first few requests and the download will be triggered. It might take a while for the download to complete depending on the internet connection. Please keep that in mind.

**Comment by jackqdyulei** [comment]
I tried on following device and didn't see any issue, is it probably a false alarm from Remote Test Lab?

Device: Samsung Galaxy S23
GMSCore version: 24.02.00

**Comment by jackqdyulei** [comment]
1. So you tested it on real local device, not from Samsung remote testlab?
2. Please provide the version of Google Play Services(com.google.android.gms) for both your local device & Samsung remote testlab
3. If possible, please provide [bug report](https://developer.android.com/studio/debug/bug-report), not the partial adb log message

**Comment by jackqdyulei** [comment]
Tested it through Samsung Remote Test Lab. It seems Samsung Remote Test Lab is using a wrong variant of GMSCore and we will work with Samsung to fix it. For real device(not through Test Lab) the module downloading should be working fine

**Comment by jackqdyulei** [comment]
Tried Samsung remote test lab and figured out that Samsung remote test lab is using the wrong gmscore variant on its Android 14 test devices, which cause this issue.

We have created internal bug to notify Samsung to fix this issue. From ML Kit side there is no issue.
