### ISSUE TITLE
[Bug report] MLKit.Initialize() fails with NullPointerException on Android 11 devices 

### ISSUE THREAD

**Issue by sangrao** [googlesamples/mlkit#777]
**Describe the bug**
To optimize app startup, we disabled ContentProvider and explicitly call MLKit.Initialize(). However, we observed crashes on some devices, most commonly chromebook + Android 11.  Note that we have integrated with both the bundled and unblunded library.

**To Reproduce**
Example Steps to reproduce the behavior in sample app:
1. Add dependency to mlkit lib specified in the SDK section below
2. set meta-data for unbundled models 
```
		<meta-data
			android:name="com.google.mlkit.vision.DEPENDENCIES"
			android:value="barcode,ocr" />
```
3. Disable Content Provider as 
`	<provider
 android:name="com.google.mlkit.common.internal.MlKitInitProvider"
 android:authorities="${applicationId}.mlkitinitprovider"
 tools:node="remove" /> `
4. In the activity, before accessing any ML kit feature invoke MLKit.Initialize(context), with context value being application context. Note, care has been taken to invoke this method only once.

**Expected behavior**
MLKit is initialized successfully. However, on certain devices crashlytics captured the below error

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.AbstractCollection.size()' on a null object reference
       at com.google.android.gms.internal.mlkit_vision_object_detection_bundled.zzar.<init>(com.google.mlkit:object-detection@@16.2.5:1)
       at com.google.android.gms.internal.mlkit_vision_object_detection_bundled.zzat.<clinit>(com.google.mlkit:object-detection@@16.2.5:1)
       at com.google.android.gms.internal.mlkit_vision_object_detection_bundled.zzat.zzh(com.google.mlkit:object-detection@@16.2.5:2)
       at com.google.android.gms.internal.mlkit_vision_object_detection_bundled.zzat.zzj(com.google.mlkit:object-detection@@16.2.5:1)
       at com.google.android.gms.internal.mlkit_vision_object_detection_bundled.zzot.<clinit>(com.google.mlkit:object-detection@@16.2.5:13)
       at com.google.mlkit.vision.objects.defaults.internal.DefaultObjectsRegistrar.getComponents(com.google.mlkit:object-detection@@16.2.5:17)
       at com.google.firebase.components.ComponentRuntime.discoverComponents(ComponentRuntime.java:117)
       at com.google.firebase.components.ComponentRuntime.<init>(ComponentRuntime.java:99)
       at com.google.firebase.components.ComponentRuntime.<init>(ComponentRuntime.java:46)
       at com.google.firebase.components.ComponentRuntime$Builder.build(ComponentRuntime.java:387)
       at com.google.mlkit.common.sdkinternal.MlKitContext.zza(com.google.mlkit:common@@17.3.0:9)
       at com.google.mlkit.common.MlKit.initialize(com.google.mlkit:common@@17.3.0:1)
```

**SDK Info:**
 - `com.google.mlkit:object-detection:16.2.5` 
 -  `com.google.android.gms:play-services-mlkit-barcode-scanning:16.2.1` 
 - `com.google.android.gms:play-services-mlkit-image-labeling:16.0.5`
 - `com.google.android.gms:play-services-mlkit-text-recognition:16.1.1`

**Smartphone:**
Mostly Chromebook

100% on Android 11 devices

**Comment by ai-plays** [comment]
Thanks for the detailed info!

The object-detection 16.2.5 is a quite old version from ~3 years ago. https://developers.google.com/ml-kit/release-notes#may_25_2021

The latest version is 17.0.1.

Do you see same error logs from newer versions?

**Comment by yuvalgnessin-qz** [comment]
We are also seeing this in our project - same parameters; it fails specifically on Chromebooks running Android 11.

In our case, the library that fails to initialize is `play-services-mlkit-barcode-scanning:18.3.1`

Full stacktrace is below. It happens on app initialization, <1 second into the user's session. We see it on Firebase but haven't been able to reproduce locally.

Hopefully this helps!

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.AbstractCollection.size()' on a null object reference
       at com.google.android.gms.internal.mlkit_vision_barcode.zzcq.<init>(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.3.1)
       at com.google.android.gms.internal.mlkit_vision_barcode.zzcs.<clinit>(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.3.1:1)
       at com.google.android.gms.internal.mlkit_vision_barcode.zzcs.zzg(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.3.1:2)
       at com.google.android.gms.internal.mlkit_vision_barcode.zzcs.zzh(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.3.1:2)
       at com.google.mlkit.vision.barcode.internal.BarcodeRegistrar.getComponents(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.3.1:11)
       at com.google.firebase.components.ComponentRuntime.discoverComponents(ComponentRuntime.java:118)
       at com.google.firebase.components.ComponentRuntime.<init>(ComponentRuntime.java:100)
       at com.google.firebase.components.ComponentRuntime.<init>(ComponentRuntime.java:46)
       at com.google.firebase.components.ComponentRuntime$Builder.build(ComponentRuntime.java:407)
       at com.google.mlkit.common.sdkinternal.MlKitContext.zzb(com.google.mlkit:common@@18.11.0:9)
       at com.google.mlkit.common.sdkinternal.MlKitContext.zza(MlKitContext.java:1)
       at com.google.mlkit.common.internal.MlKitInitProvider.onCreate(com.google.mlkit:common@@18.11.0:3)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2388)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2358)
       at com.google.mlkit.common.internal.MlKitInitProvider.attachInfo(com.google.mlkit:common@@18.11.0:3)
       at android.app.ActivityThread.installProvider(ActivityThread.java:7268)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:6809)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6726)
       at android.app.ActivityThread.access$1400(ActivityThread.java:237)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1924)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7741)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:966)
        
```

**Comment by kmayoral** [comment]
We're also still seeing this on Intel Jasper Lake Chromebooks running Android 11:

```
          Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.AbstractCollection.size()' on a null object reference
       at com.google.android.gms.internal.mlkit_vision_object_detection_bundled.zzao.<init>(com.google.mlkit:object-detection@@17.0.2)
       at com.google.android.gms.internal.mlkit_vision_object_detection_bundled.zzaq.<clinit>(com.google.mlkit:object-detection@@17.0.2:1)
       at com.google.android.gms.internal.mlkit_vision_object_detection_bundled.zzaq.zzg(com.google.mlkit:object-detection@@17.0.2:2)
       at com.google.android.gms.internal.mlkit_vision_object_detection_bundled.zzan.zzc(com.google.mlkit:object-detection@@17.0.2:1)
       at com.google.mlkit.vision.objects.defaults.internal.DefaultObjectsRegistrar.getComponents(com.google.mlkit:object-detection@@17.0.2:17)
       at com.google.firebase.components.ComponentRuntime.discoverComponents(ComponentRuntime.java:118)
       at com.google.firebase.components.ComponentRuntime.<init>(ComponentRuntime.java:100)
       at com.google.firebase.components.ComponentRuntime.<init>(ComponentRuntime.java:46)
       at com.google.firebase.components.ComponentRuntime$Builder.build(ComponentRuntime.java:407)
       at com.google.mlkit.common.sdkinternal.MlKitContext.zzb(com.google.mlkit:common@@18.11.0:9)
       at com.google.mlkit.common.sdkinternal.MlKitContext.zza(com.google.mlkit:common@@18.11.0:1)
       at com.google.mlkit.common.MlKit.initialize(com.google.mlkit:common@@18.11.0)
       at co.bird.android.App.onCreate$lambda$14(App.kt)
       at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

**Comment by 0legg** [comment]
We face it as well with Face Recognition on Intel Jasper Lake Chromebooks running Android 11:
```
Exception java.lang.ExceptionInInitializerError:
  at com.google.android.gms.internal.mlkit_vision_face.zzbn.zzh (com.google.android.gms:play-services-mlkit-face-detection@@17.1.0:2)
  at com.google.android.gms.internal.mlkit_vision_face.zzbn.zzi (com.google.android.gms:play-services-mlkit-face-detection@@17.1.0:2)
  at com.google.mlkit.vision.face.internal.FaceRegistrar.getComponents (com.google.android.gms:play-services-mlkit-face-detection@@17.1.0:10)
  at com.google.firebase.components.ComponentRuntime.discoverComponents (ComponentRuntime.java:109)
  at com.google.firebase.components.ComponentRuntime.<init> (ComponentRuntime.java:91)
  at com.google.firebase.components.ComponentRuntime.<init> (ComponentRuntime.java:45)
  at com.google.firebase.components.ComponentRuntime$Builder.build (ComponentRuntime.java:360)
  at com.google.mlkit.common.sdkinternal.MlKitContext.zzb (com.google.mlkit:common@@18.11.0:9)
  at com.google.mlkit.common.sdkinternal.MlKitContext.zza (com.google.mlkit:common@@18.11.0:1)
  at com.google.mlkit.common.internal.MlKitInitProvider.onCreate (com.google.mlkit:common@@18.11.0:3)
  at android.content.ContentProvider.attachInfo (ContentProvider.java:2388)
  at android.content.ContentProvider.attachInfo (ContentProvider.java:2358)
  at com.google.mlkit.common.internal.MlKitInitProvider.attachInfo (com.google.mlkit:common@@18.11.0:3)
  at android.app.ActivityThread.installProvider (ActivityThread.java:7268)
  at android.app.ActivityThread.installContentProviders (ActivityThread.java:6809)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6726)
  at android.app.ActivityThread.access$1400 (ActivityThread.java:237)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1924)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:223)
  at android.app.ActivityThread.main (ActivityThread.java:7741)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:592)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:958)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.AbstractCollection.size()' on a null object reference
  at com.google.android.gms.internal.mlkit_vision_face.zzbl.<init> (com.google.android.gms:play-services-mlkit-face-detection@@17.1.0:1)
  at com.google.android.gms.internal.mlkit_vision_face.zzbn.<clinit> (com.google.android.gms:play-services-mlkit-face-detection@@17.1.0:1)
```
