### ISSUE TITLE
[Bug report] Exception in Subject Segmentation on Emulator

### ISSUE THREAD

**Issue by KoheiMoroi** [googlesamples/mlkit#824]
**Describe the bug**
I am encountering an exception when trying to use the Subject Segmentation feature of MLKit on an Android emulator.
This issue occurs during the initialization of the subject segmenter module.
I would be grateful if you investigate the issue and provide guidance on how to resolve it or any workarounds.

Below is the detailed stack trace of the exception.

**Exception Stack Trace**
```
com.google.mlkit.common.MlKitException: Failed to init module subject segmenter
	at com.google.mlkit.vision.segmentation.subject.internal.zzj.load(com.google.android.gms:play-services-mlkit-subject-segmentation@@16.0.0-beta1:20)
	at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@18.10.0:4)
	at com.google.mlkit.common.sdkinternal.zzn.run(Unknown Source:10)
	at com.google.mlkit.common.sdkinternal.zzt.run(com.google.mlkit:common@@18.10.0:2)
	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@18.10.0:4)
	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@18.10.0:1)
	at com.google.mlkit.common.sdkinternal.zzi.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@18.10.0:2)
	at com.google.mlkit.common.sdkinternal.zzk.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.RemoteException: Failed to create MediaPipe image segmenter
	at com.google.android.gms.mlkit.segmentation.subject.SubjectSegmenter.c(:com.google.android.gms.optional_mlkit_subject_segmentation@242013042@24.20.13 (100400-0):1544)
	at m.awt.v(:com.google.android.gms.optional_mlkit_subject_segmentation@242013042@24.20.13 (100400-0):72)
	at m.at.onTransact(:com.google.android.gms.optional_mlkit_subject_segmentation@242013042@24.20.13 (100400-0):21)
	at android.os.Binder.transact(Binder.java:1164)
	at com.google.android.gms.internal.mlkit_vision_subject_segmentation.zza.zzc(com.google.android.gms:play-services-mlkit-subject-segmentation@@16.0.0-beta1:2)
	at com.google.android.gms.internal.mlkit_vision_subject_segmentation.zzub.zze(com.google.android.gms:play-services-mlkit-subject-segmentation@@16.0.0-beta1:2)
	at com.google.mlkit.vision.segmentation.subject.internal.zzj.load(com.google.android.gms:play-services-mlkit-subject-segmentation@@16.0.0-beta1:18)
	at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@18.10.0:4) 
	at com.google.mlkit.common.sdkinternal.zzn.run(Unknown Source:10) 
	at com.google.mlkit.common.sdkinternal.zzt.run(com.google.mlkit:common@@18.10.0:2) 
	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@18.10.0:4) 
	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@18.10.0:1) 
	at com.google.mlkit.common.sdkinternal.zzi.run(Unknown Source:2) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@18.10.0:2) 
	at com.google.mlkit.common.sdkinternal.zzk.run(Unknown Source:2) 
	at java.lang.Thread.run(Thread.java:1012) 
Caused by: com.google.mediapipe.framework.MediaPipeException: internal: CalculatorGraph::Run() failed: 
Calculator::Open() for node "mediapipe_tasks_vision_image_segmenter_imagesegmentergraph__mediapipe.tasks.TensorsToSegmentationCalculator" failed: [GL_INVALID_ENUM]: An unacceptable value is specified for an enumerated argument.: glCreateShader in third_party/tensorflow/lite/delegates/gpu/gl/gl_shader.cc:53
	at com.google.mediapipe.framework.Graph.nativeWaitUntilGraphIdle(Native Method)
	at com.google.mediapipe.framework.Graph.l(:com.google.android.gms.optional_mlkit_subject_segmentation@242013042@24.20.13 (100400-0):20)
	at com.google.android.gms.mlkit.segmentation.subject.SubjectSegmenter.c(:com.google.android.gms.optional_mlkit_subject_segmentation@242013042@24.20.13 (100400-0):1247)
	... 17 more
```

**To Reproduce**
1. Set up Android Emulator
2. Implement the Subject Segmentation feature using MLKit as per [the official documentation](https://developers.google.com/ml-kit/vision/subject-segmentation/android)
3. Attempt to initialize and use the subject segmentation module

**Expected behavior**
The subject segmentation module should initialize successfully and perform segmentation without throwing exception.

**SDK Info:**
com.google.android.gms:play-services-mlkit-subject-segmentation:16.0.0-beta1

**Smartphone:**
Emulator Spec:
```yaml
Properties
avd.ini.displayname              Pixel Tablet API 33
avd.ini.encoding                 UTF-8
AvdId                            Pixel_Tablet_API_33
disk.dataPartition.size          6442450944
fastboot.chosenSnapshotFile      
fastboot.forceChosenSnapshotBoot no
fastboot.forceColdBoot           no
fastboot.forceFastBoot           yes
hw.accelerometer                 yes
hw.arc                           false
hw.audioInput                    yes
hw.battery                       yes
hw.camera.back                   virtualscene
hw.camera.front                  emulated
hw.cpu.ncore                     4
hw.device.hash2                  MD5:3eb16c85159ad6e1cbb3263194d1a735
hw.device.manufacturer           Google
hw.device.name                   pixel_tablet
hw.dPad                          no
hw.gps                           no
hw.gpu.enabled                   yes
hw.gpu.mode                      auto
hw.initialOrientation            landscape
hw.keyboard                      yes
hw.lcd.density                   320
hw.lcd.height                    1600
hw.lcd.width                     2560
hw.mainKeys                      no
hw.ramSize                       2048
hw.sdCard                        yes
hw.sensors.orientation           yes
hw.sensors.proximity             no
hw.trackBall                     no
image.androidVersion.api         33
image.sysdir.1                   system-images/android-33/google_apis_playstore/arm64-v8a/
PlayStore.enabled                true
runtime.network.latency          none
runtime.network.speed            full
showDeviceFrame                  yes
skin.dynamic                     yes
tag.display                      Google Play
tag.id                           google_apis_playstore
vm.heapSize                      192
```

**Development Environment:**
*(For Android issue feel free to skip this section)*
- IDE Eversion: [e.g. Xcode 13.1, Android Studio 4.2]
- Laptop/Desktop: [e.g. iMac Pro (2017), HP Z840 Workstation]
- Laptop/Desktop OS/version: [e.g. macOS 12.0.1]

**Comment by SilverDestiny** [comment]
Looks like the error is the same as https://github.com/googlesamples/mlkit/issues/783

It probably means the OpenGL was too old on your emulator. You can try it on device or update the OpenGL on emulator if that's possible.

**Comment by KoheiMoroi** [comment]
@SilverDestiny 
Thank you for your response.
Let me check the following:
- Which version of OpenGL should I update to?
- Does the exception likely happen on the real devices?

**Comment by SilverDestiny** [comment]
The pipeline might expect >= ES3.1 to be working.
I haven't seen this error on the real device before.

**Comment by KoheiMoroi** [comment]
@SilverDestiny 
Thank you for your response. I am concerned that the same issue may likely happen on real devices as well.

Could you please provide more details or steps to verify if this issue could occur on real device? Specifically:
- How can we confirm the OpenGL ES version on real device?
- Are there any know limitations or configurations on real devices that could lead to this issue?
- Any additional troubleshooting steps or insights would be greatly appreciated

Thank you for your assistance in investing this further.

**Comment by KoheiMoroi** [comment]
@SilverDestiny 
Thank you for your help.
Can we ensure that the segmenter works correctly with at least OpenGL ES version 3.1?
I've also confirmed that real devices worked well.

**Comment by SilverDestiny** [comment]
Yes >= ES3.1 should work as expected

**Comment by KoheiMoroi** [comment]
@SilverDestiny 
Thank you for your significant assistance.
There is no doubt about the issue.
Thanks again.

**Comment by SilverDestiny** [comment]
You're welcome! Feel free to re-open this issue if you have any more questions!
