### ISSUE TITLE
Android face detection doesn't work in a system app

### ISSUE THREAD

**Issue by ricardaxel** [googlesamples/mlkit#93]
Hello, I'm currently working on a system app that would run on an AOSP box. 

I tried to recognize faces with cameraX, and got this error : `E/MobileVisionBase: Error preloading model resource`  when calling _process_ method on the **FaceDetector**

The sample app works fine on the box so I assume that my problem comes from the system app status. For information I use the **bundle model**.

Here is the full trace : 

```
2020-07-27 15:53:07.084 11115-11115/fr.technosens.eliodroid.ebox E/MobileVisionBase: Error preloading model resource
    com.google.mlkit.common.MlKitException: Internal error has occurred when executing ML Kit tasks
        at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@16.0.0:28)
        at com.google.mlkit.common.sdkinternal.zzn.call(Unknown Source:6)
        at com.google.mlkit.common.sdkinternal.zzm.run(com.google.mlkit:common@@16.0.0:5)
        at com.google.mlkit.common.sdkinternal.zzq.run(com.google.mlkit:common@@16.0.0:3)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@16.0.0:24)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zza(com.google.mlkit:common@@16.0.0:30)
        at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.SecurityException: Failed to find provider com.google.android.gsf.gservices for user 0; expected to find a valid ContentProvider for this authority
        at android.os.Parcel.readException(Parcel.java:1951)
        at android.os.Parcel.readException(Parcel.java:1897)
        at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:768)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1924)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1913)
        at com.google.android.gms.internal.vision.zzba.<init>(com.google.android.gms:play-services-vision-common@@19.1.0:11)
        at com.google.android.gms.internal.vision.zzba.zze(com.google.android.gms:play-services-vision-common@@19.1.0:5)
        at com.google.android.gms.internal.vision.zzbj.zzae(com.google.android.gms:play-services-vision-common@@19.1.0:71)
        at com.google.android.gms.internal.vision.zzbj.get(com.google.android.gms:play-services-vision-common@@19.1.0:50)
        at com.google.android.gms.internal.vision.zzlb.zzjq(com.google.android.gms:play-services-vision-common@@19.1.0:2)
        at com.google.android.gms.internal.vision.zzla.zzjq(com.google.android.gms:play-services-vision-common@@19.1.0:1)
        at com.google.android.gms.internal.vision.zzs.<init>(com.google.android.gms:play-services-vision-common@@19.1.0:14)
        at com.google.android.gms.vision.face.internal.client.zzb.<init>(com.google.android.gms:play-services-vision@@20.1.0:1)
        at com.google.android.gms.vision.face.FaceDetector$Builder.build(com.google.android.gms:play-services-vision@@20.1.0:40)
        at com.google.mlkit.vision.face.internal.zzd.load(com.google.android.gms:play-services-mlkit-face-detection@@16.1.0:37)
        at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@16.0.0:22)
        at com.google.mlkit.common.sdkinternal.zzn.call(Unknown Source:6) 
        at com.google.mlkit.common.sdkinternal.zzm.run(com.google.mlkit:common@@16.0.0:5) 
        at com.google.mlkit.common.sdkinternal.zzq.run(com.google.mlkit:common@@16.0.0:3) 
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@16.0.0:24) 
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zza(com.google.mlkit:common@@16.0.0:30) 
        at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
```

Any idea to solve this issue ? Or did I missed something ?

Thanks

**Comment by calren** [comment]
The models are downloaded from play services, so I would guess that's why the system app is complaining about not knowing where to download the models from. 

Which dependency are you using for face detection? You could try using the dependency that already has the model bundled to avoid having to download them
`implementation 'com.google.mlkit:face-detection:16.0.0'`

More info about it here: https://developers.google.com/ml-kit/vision/face-detection/android

**Comment by ricardaxel** [comment]
> The models are downloaded from play services, so I would guess that's why the system app is complaining about not knowing where to download the models from.
> 
> Which dependency are you using for face detection? You could try using the dependency that already has the model bundled to avoid having to download them
> `implementation 'com.google.mlkit:face-detection:16.0.0'`
> 
> More info about it here: https://developers.google.com/ml-kit/vision/face-detection/android

I already use this one so I don't see why it would want to download them again. And as I said the sample app works on the AOSP box so I don't think this problem comes from that.

**Comment by swiyu** [comment]
Looks like the model does not exist. Are you use the bundled model or use the model from Google Play Services? 

See [here](https://developers.google.com/ml-kit/vision/face-detection/android#before-you-begin) for the two different dependencies. 

By using the bundled model, you should be able to detect the faces.

**Comment by ricardaxel** [comment]
> Looks like the model does not exist. Are you using the bundled model or use the model from Google Play Services?
> 
> See [here](https://developers.google.com/ml-kit/vision/face-detection/android#before-you-begin) for the two different dependencies.
> 
> By using the bundled model, you should be able to detect the faces.

I use the bundled model so I'm surprised to see that the model is not found.

**Comment by sheepmaster** [comment]
FYI, unobfuscated stack trace is [here](https://paste.googleplex.com/5380075413307392) (internal only, sry). It looks like even though the app is using the bundled model, there is a code path that checks whether to use a particular variant of the Google Play Services model, which fails to find a ContentProvider in Google Play Services. From searching the error message, it seems that this does in fact happen when Google Play Services is not installed, but maybe there is something particular about your configuration that causes the exception but doesn't in the "usual" AOSP configuration. In any case, this code path has recently been removed, so the crash should go away in the next release of ML Kit. Stay tuned :)

**Comment by ricardaxel** [comment]
> FYI, unobfuscated stack trace is [here](https://paste.googleplex.com/5380075413307392) (internal only, sry). It looks like even though the app is using the bundled model, there is a code path that checks whether to use a particular variant of the Google Play Services model, which fails to find a ContentProvider in Google Play Services. From searching the error message, it seems that this does in fact happen when Google Play Services is not installed, but maybe there is something particular about your configuration that causes the exception but doesn't in the "usual" AOSP configuration. In any case, this code path has recently been removed, so the crash should go away in the next release of ML Kit. Stay tuned :)

Thanks for your reply ! So nothing more to do for the moment. Any hint about the next release date ?

**Comment by sheepmaster** [comment]
So, a new ML Kit release came out yesterday, but the release doesn't include `com.google.android.gms:play-services-vision`, which is where the fix is. I've filed an internal bug to include it in the next release, which should hopefully be in a few weeks.
