### ISSUE TITLE
Internal Exception when Scanning barcodes through CameraX API

### ISSUE THREAD

**Issue by Davoleo** [googlesamples/mlkit#95]
source code of my project: https://github.com/Davoleo/BarcodeStock

The exception I'm getting:
```
E/BarcodeStock: Barcode detection failed!
    com.google.mlkit.common.MlKitException: Internal error has occurred when executing ML Kit tasks
        at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@16.0.0:28)
        at com.google.mlkit.common.sdkinternal.zzn.call(Unknown Source:6)
        at com.google.mlkit.common.sdkinternal.zzm.run(com.google.mlkit:common@@16.0.0:5)
        at com.google.mlkit.common.sdkinternal.zzq.run(com.google.mlkit:common@@16.0.0:3)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@16.0.0:24)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zza(com.google.mlkit:common@@16.0.0:30)
        at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: java.lang.IllegalArgumentException: Null image data supplied.
        at com.google.android.gms.vision.Frame$Builder.setImageData(com.google.android.gms:play-services-vision-common@@19.1.0:23)
        at com.google.mlkit.vision.barcode.internal.zzf.zza(com.google.android.gms:play-services-mlkit-barcode-scanning@@16.1.0:75)
        at com.google.mlkit.vision.barcode.internal.zzf.zzb(com.google.android.gms:play-services-mlkit-barcode-scanning@@16.1.0:83)
        at com.google.mlkit.vision.barcode.internal.zzf.run(com.google.android.gms:play-services-mlkit-barcode-scanning@@16.1.0:143)
        at com.google.mlkit.vision.common.internal.MobileVisionBase.zza(com.google.mlkit:vision-common@@16.0.0:23)
        at com.google.mlkit.vision.common.internal.zzb.call(Unknown Source:4)
        at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@16.0.0:26)
        at com.google.mlkit.common.sdkinternal.zzn.call(Unknown Source:6) 
        at com.google.mlkit.common.sdkinternal.zzm.run(com.google.mlkit:common@@16.0.0:5) 
        at com.google.mlkit.common.sdkinternal.zzq.run(com.google.mlkit:common@@16.0.0:3) 
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@16.0.0:24) 
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zza(com.google.mlkit:common@@16.0.0:30) 
        at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2) 
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:784) 
```

this line is spammed repeatedly as well:
```
I/GRALLOC: LockFlexLayout: baseFormat: 11, yStride: 640, ySize: 307200, uOffset: 307200,  uStride: 640
```

The analyzer calls the onFailure callback function and logs this exception which is first thrown in the `com.google.android.gms.vision.Frame` class although I didn't manage to understand which part of my code is behaving wrong because most of the classes are decompiled and have obfuscated variable names (var2, var5, zza)
![image](https://user-images.githubusercontent.com/24458276/88661638-22e2f000-d0d9-11ea-830b-5ce9e996213b.png)

this is the main class that controls the Camera and the analysis process
https://github.com/Davoleo/BarcodeStock/blob/master/app/src/main/java/io/github/davoleo/barcodestock/scanner/BarcodeScannerActivity.kt

What I'm asking here is if anyone that has encountered this issue or that is familiar with mlkit's source code could give me any pointers about fixing this kind of issue

**Comment by sheepmaster** [comment]
In your [code](https://github.com/Davoleo/BarcodeStock/blob/18597f7bc8921af1d3145646cd38b27c18eb3ee1/app/src/main/java/io/github/davoleo/barcodestock/scanner/BarcodeScannerActivity.kt#L139), you are calling `imageProxy.close()` immediately after starting to process the image. You need to delay that call until the `BarcodeScanner` has finished processing the image (because the image is processed asynchronously, that can happen at a later point). One simple way to do that is to add an `onCompleteListener` alongside the `onSucessListener` and `onFailureListener` (so that it is called in both cases) and close the `ImageProxy` there.

I've also noticed that you are getting a new `BarcodeScanner` instance every time you are processing a frame, which can lead to resource leaks for the underlying model. Instead, you should keep a single `BarcodeScanner` instance around and close it when your `Activity` is destroyed. `BarcodeScanner` implements the `LifecycleObserver` interface, so you can simply add it as an observer of the `Activity`'s lifecycle: `lifecycle.addObserver(scanner)`.

**Comment by Davoleo** [comment]
oh ok, thanks for the code review and explanation
